//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

#pragma warning disable 414
namespace ChecklistReportLegislativo {
    
    
    /// 
    [Microsoft.VisualStudio.Tools.Applications.Runtime.StartupObjectAttribute(0)]
    [global::System.Security.Permissions.PermissionSetAttribute(global::System.Security.Permissions.SecurityAction.Demand, Name="FullTrust")]
    public sealed partial class ThisDocument : Microsoft.Office.Tools.Word.DocumentBase {
        
        internal Microsoft.Office.Tools.ActionsPane ActionsPane;
        
        internal Microsoft.Office.Tools.Word.ComboBoxContentControl comboBoxContentControl1;
        
        internal Microsoft.Office.Tools.Word.DatePickerContentControl datePickerContentControl1;
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "15.0.0.0")]
        private global::System.Object missing = global::System.Type.Missing;
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "15.0.0.0")]
        internal Microsoft.Office.Interop.Word.Application ThisApplication;
        
        internal Microsoft.Office.Tools.Word.Controls.CheckBox checkBox01;
        
        internal Microsoft.Office.Tools.Word.Controls.CheckBox checkBox02;
        
        internal Microsoft.Office.Tools.Word.Controls.CheckBox checkBox03;
        
        internal Microsoft.Office.Tools.Word.Controls.CheckBox checkBox04;
        
        internal Microsoft.Office.Tools.Word.Controls.CheckBox checkBox05;
        
        internal Microsoft.Office.Tools.Word.Controls.CheckBox checkBox06;
        
        internal Microsoft.Office.Tools.Word.Controls.CheckBox checkBox07;
        
        internal Microsoft.Office.Tools.Word.Controls.CheckBox checkBox08;
        
        internal Microsoft.Office.Tools.Word.Controls.CheckBox checkBox09;
        
        internal Microsoft.Office.Tools.Word.Controls.CheckBox checkBox10;
        
        internal Microsoft.Office.Tools.Word.Controls.CheckBox checkBox11;
        
        internal Microsoft.Office.Tools.Word.Controls.CheckBox checkBox12;
        
        internal Microsoft.Office.Tools.Word.Controls.CheckBox checkBox13;
        
        internal Microsoft.Office.Tools.Word.Controls.CheckBox checkBox14;
        
        internal Microsoft.Office.Tools.Word.Controls.CheckBox checkBox15;
        
        internal Microsoft.Office.Tools.Word.Controls.CheckBox checkBox16;
        
        internal Microsoft.Office.Tools.Word.Controls.CheckBox checkBox17;
        
        internal Microsoft.Office.Tools.Word.Controls.CheckBox checkBox18;
        
        internal Microsoft.Office.Tools.Word.Controls.CheckBox checkBox19;
        
        internal Microsoft.Office.Tools.Word.Controls.CheckBox checkBox20;
        
        internal Microsoft.Office.Tools.Word.Controls.CheckBox checkBox21;
        
        internal Microsoft.Office.Tools.Word.Controls.CheckBox checkBox22;
        
        internal Microsoft.Office.Tools.Word.Controls.CheckBox checkBox23;
        
        internal Microsoft.Office.Tools.Word.Controls.CheckBox checkBox24;
        
        internal Microsoft.Office.Tools.Word.Controls.CheckBox checkBox25;
        
        internal Microsoft.Office.Tools.Word.Controls.CheckBox checkBox26;
        
        internal Microsoft.Office.Tools.Word.Controls.CheckBox checkBox29;
        
        internal Microsoft.Office.Tools.Word.Controls.CheckBox checkBox28;
        
        internal Microsoft.Office.Tools.Word.Controls.CheckBox checkBox27;
        
        internal Microsoft.Office.Tools.Word.Controls.CheckBox checkBox30;
        
        internal Microsoft.Office.Tools.Word.Controls.CheckBox checkBox31;
        
        internal Microsoft.Office.Tools.Word.Controls.CheckBox checkBox32;
        
        internal Microsoft.Office.Tools.Word.Controls.CheckBox checkBox38;
        
        internal Microsoft.Office.Tools.Word.Controls.CheckBox checkBox37;
        
        internal Microsoft.Office.Tools.Word.Controls.CheckBox checkBox36;
        
        internal Microsoft.Office.Tools.Word.Controls.CheckBox checkBox35;
        
        internal Microsoft.Office.Tools.Word.Controls.CheckBox checkBox34;
        
        internal Microsoft.Office.Tools.Word.Controls.CheckBox checkBox33;
        
        internal Microsoft.Office.Tools.Word.Controls.CheckBox checkBox39;
        
        internal Microsoft.Office.Tools.Word.Controls.CheckBox checkBox40;
        
        internal Microsoft.Office.Tools.Word.Controls.CheckBox checkBox41;
        
        internal Microsoft.Office.Tools.Word.Controls.CheckBox checkBox42;
        
        internal Microsoft.Office.Tools.Word.Controls.CheckBox checkBox43;
        
        internal Microsoft.Office.Tools.Word.Controls.CheckBox checkBox44;
        
        internal Microsoft.Office.Tools.Word.Controls.CheckBox checkBox45;
        
        internal Microsoft.Office.Tools.Word.Controls.CheckBox checkBox46;
        
        internal Microsoft.Office.Tools.Word.Controls.CheckBox checkBox47;
        
        internal Microsoft.Office.Tools.Word.Controls.CheckBox checkBox48;
        
        internal Microsoft.Office.Tools.Word.Controls.CheckBox checkBox49;
        
        internal Microsoft.Office.Tools.Word.Controls.CheckBox checkBox50;
        
        internal Microsoft.Office.Tools.Word.Controls.CheckBox checkBox51;
        
        internal Microsoft.Office.Tools.Word.Controls.CheckBox checkBox52;
        
        internal Microsoft.Office.Tools.Word.Controls.CheckBox checkBox53;
        
        internal Microsoft.Office.Tools.Word.Controls.CheckBox checkBox54;
        
        internal Microsoft.Office.Tools.Word.Controls.CheckBox checkBox55;
        
        internal Microsoft.Office.Tools.Word.Controls.CheckBox checkBox56;
        
        internal Microsoft.Office.Tools.Word.Controls.CheckBox checkBox57;
        
        internal Microsoft.Office.Tools.Word.Controls.CheckBox checkBox58;
        
        internal Microsoft.Office.Tools.Word.Controls.CheckBox checkBox59;
        
        internal Microsoft.Office.Tools.Word.Controls.CheckBox checkBox62;
        
        internal Microsoft.Office.Tools.Word.Controls.CheckBox checkBox60;
        
        internal Microsoft.Office.Tools.Word.Controls.CheckBox checkBox61;
        
        internal Microsoft.Office.Tools.Word.Controls.CheckBox checkBox63;
        
        internal Microsoft.Office.Tools.Word.Controls.CheckBox checkBox64;
        
        internal Microsoft.Office.Tools.Word.Controls.CheckBox checkBox65;
        
        internal Microsoft.Office.Tools.Word.Controls.CheckBox checkBox66;
        
        internal Microsoft.Office.Tools.Word.Controls.CheckBox checkBox67;
        
        internal Microsoft.Office.Tools.Word.Controls.CheckBox checkBox68;
        
        internal Microsoft.Office.Tools.Word.Controls.CheckBox checkBox69;
        
        internal Microsoft.Office.Tools.Word.Controls.CheckBox checkBox70;
        
        internal Microsoft.Office.Tools.Word.Controls.CheckBox checkBox71;
        
        internal Microsoft.Office.Tools.Word.Controls.CheckBox checkBox72;
        
        internal Microsoft.Office.Tools.Word.Controls.CheckBox checkBox73;
        
        internal Microsoft.Office.Tools.Word.Controls.CheckBox checkBox74;
        
        internal Microsoft.Office.Tools.Word.Controls.CheckBox checkBox75;
        
        internal Microsoft.Office.Tools.Word.Controls.CheckBox checkBox76;
        
        internal Microsoft.Office.Tools.Word.Controls.CheckBox checkBox77;
        
        internal Microsoft.Office.Tools.Word.Controls.CheckBox checkBox78;
        
        internal Microsoft.Office.Tools.Word.Controls.CheckBox checkBox79;
        
        internal Microsoft.Office.Tools.Word.Controls.CheckBox checkBox80;
        
        internal Microsoft.Office.Tools.Word.Controls.CheckBox checkBox81;
        
        internal Microsoft.Office.Tools.Word.Controls.CheckBox checkBox82;
        
        internal Microsoft.Office.Tools.Word.Controls.CheckBox checkBox83;
        
        internal Microsoft.Office.Tools.Word.Controls.CheckBox checkBox84;
        
        internal Microsoft.Office.Tools.Word.Controls.CheckBox checkBox85;
        
        internal Microsoft.Office.Tools.Word.Controls.CheckBox checkBox86;
        
        internal Microsoft.Office.Tools.Word.Controls.CheckBox checkBox87;
        
        internal Microsoft.Office.Tools.Word.Controls.CheckBox checkBox88;
        
        internal Microsoft.Office.Tools.Word.Controls.CheckBox checkBox89;
        
        internal Microsoft.Office.Tools.Word.Controls.CheckBox checkBox90;
        
        internal Microsoft.Office.Tools.Word.Controls.CheckBox checkBox91;
        
        internal Microsoft.Office.Tools.Word.Controls.CheckBox checkBox92;
        
        internal Microsoft.Office.Tools.Word.Controls.CheckBox checkBox93;
        
        internal Microsoft.Office.Tools.Word.Controls.CheckBox checkBox94;
        
        internal Microsoft.Office.Tools.Word.Controls.CheckBox checkBox95;
        
        internal Microsoft.Office.Tools.Word.Controls.CheckBox checkBox96;
        
        internal Microsoft.Office.Tools.Word.Controls.Button btnGerarXML;
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        public ThisDocument(global::Microsoft.Office.Tools.Word.Factory factory, global::System.IServiceProvider serviceProvider) : 
                base(factory, serviceProvider, "ThisDocument", "ThisDocument") {
            Globals.Factory = factory;
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "15.0.0.0")]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        protected override void Initialize() {
            base.Initialize();
            this.ThisApplication = this.GetHostItem<Microsoft.Office.Interop.Word.Application>(typeof(Microsoft.Office.Interop.Word.Application), "Application");
            Globals.ThisDocument = this;
            global::System.Windows.Forms.Application.EnableVisualStyles();
            this.InitializeCachedData();
            this.InitializeControls();
            this.InitializeComponents();
            this.InitializeData();
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "15.0.0.0")]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        protected override void FinishInitialization() {
            this.InternalStartup();
            this.OnStartup();
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "15.0.0.0")]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        protected override void InitializeDataBindings() {
            this.BeginInitialization();
            this.BindToData();
            this.EndInitialization();
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "15.0.0.0")]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void InitializeCachedData() {
            if ((this.DataHost == null)) {
                return;
            }
            if (this.DataHost.IsCacheInitialized) {
                this.DataHost.FillCachedData(this);
            }
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "15.0.0.0")]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void InitializeData() {
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "15.0.0.0")]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void BindToData() {
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        private void StartCaching(string MemberName) {
            this.DataHost.StartCaching(this, MemberName);
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        private void StopCaching(string MemberName) {
            this.DataHost.StopCaching(this, MemberName);
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        private bool IsCached(string MemberName) {
            return this.DataHost.IsCached(this, MemberName);
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "15.0.0.0")]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void BeginInitialization() {
            this.BeginInit();
            this.ActionsPane.BeginInit();
            this.comboBoxContentControl1.BeginInit();
            this.datePickerContentControl1.BeginInit();
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "15.0.0.0")]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void EndInitialization() {
            this.datePickerContentControl1.EndInit();
            this.comboBoxContentControl1.EndInit();
            this.ActionsPane.EndInit();
            this.EndInit();
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "15.0.0.0")]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void InitializeControls() {
            this.ActionsPane = Globals.Factory.CreateActionsPane(null, null, "ActionsPane", "ActionsPane", this);
            this.comboBoxContentControl1 = Globals.Factory.CreateComboBoxContentControl(null, null, "2897304870", "comboBoxContentControl1", this);
            this.datePickerContentControl1 = Globals.Factory.CreateDatePickerContentControl(null, null, "4179056737", "datePickerContentControl1", this);
            this.checkBox01 = new Microsoft.Office.Tools.Word.Controls.CheckBox(Globals.Factory, this.ItemProvider, this.HostContext, "0D48B359C0535504487095C602615C76543280", "0D48B359C0535504487095C602615C76543280", this, "checkBox01");
            this.checkBox02 = new Microsoft.Office.Tools.Word.Controls.CheckBox(Globals.Factory, this.ItemProvider, this.HostContext, "177B964421535F14F401BE641806797B2C6721", "177B964421535F14F401BE641806797B2C6721", this, "checkBox02");
            this.checkBox03 = new Microsoft.Office.Tools.Word.Controls.CheckBox(Globals.Factory, this.ItemProvider, this.HostContext, "2AC6A53B823F012425928521274F190AC49132", "2AC6A53B823F012425928521274F190AC49132", this, "checkBox03");
            this.checkBox04 = new Microsoft.Office.Tools.Word.Controls.CheckBox(Globals.Factory, this.ItemProvider, this.HostContext, "322F545EF3F6A034CAC3935635D74ABB089393", "322F545EF3F6A034CAC3935635D74ABB089393", this, "checkBox04");
            this.checkBox05 = new Microsoft.Office.Tools.Word.Controls.CheckBox(Globals.Factory, this.ItemProvider, this.HostContext, "4715C3D1A44DE644D154A7E14142AFDB11B0A4", "4715C3D1A44DE644D154A7E14142AFDB11B0A4", this, "checkBox05");
            this.checkBox06 = new Microsoft.Office.Tools.Word.Controls.CheckBox(Globals.Factory, this.ItemProvider, this.HostContext, "572DAF8EB58DEA54DA85B3D2542D1DA870D735", "572DAF8EB58DEA54DA85B3D2542D1DA870D735", this, "checkBox06");
            this.checkBox07 = new Microsoft.Office.Tools.Word.Controls.CheckBox(Globals.Factory, this.ItemProvider, this.HostContext, "6A1988C8E67C2D64AA26B79C6269B99241EDC6", "6A1988C8E67C2D64AA26B79C6269B99241EDC6", this, "checkBox07");
            this.checkBox08 = new Microsoft.Office.Tools.Word.Controls.CheckBox(Globals.Factory, this.ItemProvider, this.HostContext, "7B08ED5B472D5174D707B22D77858A728D4387", "7B08ED5B472D5174D707B22D77858A728D4387", this, "checkBox08");
            this.checkBox09 = new Microsoft.Office.Tools.Word.Controls.CheckBox(Globals.Factory, this.ItemProvider, this.HostContext, "8F007C56D87ED384C598922886219A382596A8", "8F007C56D87ED384C598922886219A382596A8", this, "checkBox09");
            this.checkBox10 = new Microsoft.Office.Tools.Word.Controls.CheckBox(Globals.Factory, this.ItemProvider, this.HostContext, "909CB8A1B9608A94F9D9A6CE93F222622E5E19", "909CB8A1B9608A94F9D9A6CE93F222622E5E19", this, "checkBox10");
            this.checkBox11 = new Microsoft.Office.Tools.Word.Controls.CheckBox(Globals.Factory, this.ItemProvider, this.HostContext, "11EFB81501CA55147F0186481FF100EB04C4F1", "11EFB81501CA55147F0186481FF100EB04C4F1", this, "checkBox11");
            this.checkBox12 = new Microsoft.Office.Tools.Word.Controls.CheckBox(Globals.Factory, this.ItemProvider, this.HostContext, "127E91DFB18897143FF1886D135464B79A3C71", "127E91DFB18897143FF1886D135464B79A3C71", this, "checkBox12");
            this.checkBox13 = new Microsoft.Office.Tools.Word.Controls.CheckBox(Globals.Factory, this.ItemProvider, this.HostContext, "1F3B7950714151148FE1898C1297BFA7DF9731", "1F3B7950714151148FE1898C1297BFA7DF9731", this, "checkBox13");
            this.checkBox14 = new Microsoft.Office.Tools.Word.Controls.CheckBox(Globals.Factory, this.ItemProvider, this.HostContext, "1400E4D461D08C1419C1AEEA14F6233B8679C1", "1400E4D461D08C1419C1AEEA14F6233B8679C1", this, "checkBox14");
            this.checkBox15 = new Microsoft.Office.Tools.Word.Controls.CheckBox(Globals.Factory, this.ItemProvider, this.HostContext, "1CA2B87F31864114B931AAF71075E785E10D21", "1CA2B87F31864114B931AAF71075E785E10D21", this, "checkBox15");
            this.checkBox16 = new Microsoft.Office.Tools.Word.Controls.CheckBox(Globals.Factory, this.ItemProvider, this.HostContext, "140E69FC21C83914D831BDAE172AD7237E1EF1", "140E69FC21C83914D831BDAE172AD7237E1EF1", this, "checkBox16");
            this.checkBox17 = new Microsoft.Office.Tools.Word.Controls.CheckBox(Globals.Factory, this.ItemProvider, this.HostContext, "14E2A9FDA13C8814D2B1889A1DC216EFE4B6C1", "14E2A9FDA13C8814D2B1889A1DC216EFE4B6C1", this, "checkBox17");
            this.checkBox18 = new Microsoft.Office.Tools.Word.Controls.CheckBox(Globals.Factory, this.ItemProvider, this.HostContext, "121989741145F61408B1BB2D1A5F1775323C61", "121989741145F61408B1BB2D1A5F1775323C61", this, "checkBox18");
            this.checkBox19 = new Microsoft.Office.Tools.Word.Controls.CheckBox(Globals.Factory, this.ItemProvider, this.HostContext, "1F86D23E711D5714C011953F1EB5B5F1581BD1", "1F86D23E711D5714C011953F1EB5B5F1581BD1", this, "checkBox19");
            this.checkBox20 = new Microsoft.Office.Tools.Word.Controls.CheckBox(Globals.Factory, this.ItemProvider, this.HostContext, "1DC5939751559C14568197091CE31B0AECBCE1", "1DC5939751559C14568197091CE31B0AECBCE1", this, "checkBox20");
            this.checkBox21 = new Microsoft.Office.Tools.Word.Controls.CheckBox(Globals.Factory, this.ItemProvider, this.HostContext, "278F4ECA52DB522434B28530295BA5BB447902", "278F4ECA52DB522434B28530295BA5BB447902", this, "checkBox21");
            this.checkBox22 = new Microsoft.Office.Tools.Word.Controls.CheckBox(Globals.Factory, this.ItemProvider, this.HostContext, "2992B43B229D6D24BA22BC3120CA7F15B4A7E2", "2992B43B229D6D24BA22BC3120CA7F15B4A7E2", this, "checkBox22");
            this.checkBox23 = new Microsoft.Office.Tools.Word.Controls.CheckBox(Globals.Factory, this.ItemProvider, this.HostContext, "2742F1B5C239C724C882A95523D2779E320F92", "2742F1B5C239C724C882A95523D2779E320F92", this, "checkBox23");
            this.checkBox24 = new Microsoft.Office.Tools.Word.Controls.CheckBox(Globals.Factory, this.ItemProvider, this.HostContext, "2C837F3A02304624B9D2820B2A0F980BFF7FD2", "2C837F3A02304624B9D2820B2A0F980BFF7FD2", this, "checkBox24");
            this.checkBox25 = new Microsoft.Office.Tools.Word.Controls.CheckBox(Globals.Factory, this.ItemProvider, this.HostContext, "26871D3822FDDB24FCE2A0232F82B517EA3592", "26871D3822FDDB24FCE2A0232F82B517EA3592", this, "checkBox25");
            this.checkBox26 = new Microsoft.Office.Tools.Word.Controls.CheckBox(Globals.Factory, this.ItemProvider, this.HostContext, "20208EB3326A0624D702BB4627247C33D850E2", "20208EB3326A0624D702BB4627247C33D850E2", this, "checkBox26");
            this.checkBox29 = new Microsoft.Office.Tools.Word.Controls.CheckBox(Globals.Factory, this.ItemProvider, this.HostContext, "2FC832C782D536242522B5D72817D74CB4C352", "2FC832C782D536242522B5D72817D74CB4C352", this, "checkBox29");
            this.checkBox28 = new Microsoft.Office.Tools.Word.Controls.CheckBox(Globals.Factory, this.ItemProvider, this.HostContext, "29C98A70B21889241F92875B2F7108ECCB65A2", "29C98A70B21889241F92875B2F7108ECCB65A2", this, "checkBox28");
            this.checkBox27 = new Microsoft.Office.Tools.Word.Controls.CheckBox(Globals.Factory, this.ItemProvider, this.HostContext, "272E9DF3F22A0C24CA9290FF24194D882BCCE2", "272E9DF3F22A0C24CA9290FF24194D882BCCE2", this, "checkBox27");
            this.checkBox30 = new Microsoft.Office.Tools.Word.Controls.CheckBox(Globals.Factory, this.ItemProvider, this.HostContext, "29F63C8A92E94024D912A3552034FF23BEEBA2", "29F63C8A92E94024D912A3552034FF23BEEBA2", this, "checkBox30");
            this.checkBox31 = new Microsoft.Office.Tools.Word.Controls.CheckBox(Globals.Factory, this.ItemProvider, this.HostContext, "3D072C93D30DEF34D8638CE53300E6E2AB20C3", "3D072C93D30DEF34D8638CE53300E6E2AB20C3", this, "checkBox31");
            this.checkBox32 = new Microsoft.Office.Tools.Word.Controls.CheckBox(Globals.Factory, this.ItemProvider, this.HostContext, "36FB9DC27363CE3482F396A13052CCF49F1383", "36FB9DC27363CE3482F396A13052CCF49F1383", this, "checkBox32");
            this.checkBox38 = new Microsoft.Office.Tools.Word.Controls.CheckBox(Globals.Factory, this.ItemProvider, this.HostContext, "3A75BFBD330AAF34051394F032D0FC1C2D2AA3", "3A75BFBD330AAF34051394F032D0FC1C2D2AA3", this, "checkBox38");
            this.checkBox37 = new Microsoft.Office.Tools.Word.Controls.CheckBox(Globals.Factory, this.ItemProvider, this.HostContext, "37536EF5538AC034C7C3B3D6336566E3B4A0C3", "37536EF5538AC034C7C3B3D6336566E3B4A0C3", this, "checkBox37");
            this.checkBox36 = new Microsoft.Office.Tools.Word.Controls.CheckBox(Globals.Factory, this.ItemProvider, this.HostContext, "3DF6D0FE53E0BF34C82394963114C76516A0C3", "3DF6D0FE53E0BF34C82394963114C76516A0C3", this, "checkBox36");
            this.checkBox35 = new Microsoft.Office.Tools.Word.Controls.CheckBox(Globals.Factory, this.ItemProvider, this.HostContext, "3192AABE434D013499D3A5323267F381923913", "3192AABE434D013499D3A5323267F381923913", this, "checkBox35");
            this.checkBox34 = new Microsoft.Office.Tools.Word.Controls.CheckBox(Globals.Factory, this.ItemProvider, this.HostContext, "3D6DC4BA13DC80343353869239402745AB6F93", "3D6DC4BA13DC80343353869239402745AB6F93", this, "checkBox34");
            this.checkBox33 = new Microsoft.Office.Tools.Word.Controls.CheckBox(Globals.Factory, this.ItemProvider, this.HostContext, "3EC45494838BE534EDD383AD34E5CB12714403", "3EC45494838BE534EDD383AD34E5CB12714403", this, "checkBox33");
            this.checkBox39 = new Microsoft.Office.Tools.Word.Controls.CheckBox(Globals.Factory, this.ItemProvider, this.HostContext, "3A790B74C31B4F343873BB41343AFC485087B3", "3A790B74C31B4F343873BB41343AFC485087B3", this, "checkBox39");
            this.checkBox40 = new Microsoft.Office.Tools.Word.Controls.CheckBox(Globals.Factory, this.ItemProvider, this.HostContext, "3F19FA7F639722343D13B64C3E8856EE639FA3", "3F19FA7F639722343D13B64C3E8856EE639FA3", this, "checkBox40");
            this.checkBox41 = new Microsoft.Office.Tools.Word.Controls.CheckBox(Globals.Factory, this.ItemProvider, this.HostContext, "41D4DC36B45C0944D23497964BFB5709D069D4", "41D4DC36B45C0944D23497964BFB5709D069D4", this, "checkBox41");
            this.checkBox42 = new Microsoft.Office.Tools.Word.Controls.CheckBox(Globals.Factory, this.ItemProvider, this.HostContext, "4C2637BAB4F4914490E4961F476513AA7FC804", "4C2637BAB4F4914490E4961F476513AA7FC804", this, "checkBox42");
            this.checkBox43 = new Microsoft.Office.Tools.Word.Controls.CheckBox(Globals.Factory, this.ItemProvider, this.HostContext, "48C96B62341B864450B4865A4AE58B85163134", "48C96B62341B864450B4865A4AE58B85163134", this, "checkBox43");
            this.checkBox44 = new Microsoft.Office.Tools.Word.Controls.CheckBox(Globals.Factory, this.ItemProvider, this.HostContext, "469B6AEB448C0C44F32492D84C84B568164404", "469B6AEB448C0C44F32492D84C84B568164404", this, "checkBox44");
            this.checkBox45 = new Microsoft.Office.Tools.Word.Controls.CheckBox(Globals.Factory, this.ItemProvider, this.HostContext, "4BBD65CE54505B44CE74857F4E70403DDFFDE4", "4BBD65CE54505B44CE74857F4E70403DDFFDE4", this, "checkBox45");
            this.checkBox46 = new Microsoft.Office.Tools.Word.Controls.CheckBox(Globals.Factory, this.ItemProvider, this.HostContext, "47A15531F4EDE7443AA481AC4C6ED863452EC4", "47A15531F4EDE7443AA481AC4C6ED863452EC4", this, "checkBox46");
            this.checkBox47 = new Microsoft.Office.Tools.Word.Controls.CheckBox(Globals.Factory, this.ItemProvider, this.HostContext, "4FD8EE0404BF604473E48A644BF6DF4E881CD4", "4FD8EE0404BF604473E48A644BF6DF4E881CD4", this, "checkBox47");
            this.checkBox48 = new Microsoft.Office.Tools.Word.Controls.CheckBox(Globals.Factory, this.ItemProvider, this.HostContext, "4D0FB418949D9844E6C493F44D27C3B1C70E84", "4D0FB418949D9844E6C493F44D27C3B1C70E84", this, "checkBox48");
            this.checkBox49 = new Microsoft.Office.Tools.Word.Controls.CheckBox(Globals.Factory, this.ItemProvider, this.HostContext, "40C8E112F47BDF445E74AD4F4BE9B7C18F0D04", "40C8E112F47BDF445E74AD4F4BE9B7C18F0D04", this, "checkBox49");
            this.checkBox50 = new Microsoft.Office.Tools.Word.Controls.CheckBox(Globals.Factory, this.ItemProvider, this.HostContext, "4969F9C7C44CC4442AB49BF2499BF140F27284", "4969F9C7C44CC4442AB49BF2499BF140F27284", this, "checkBox50");
            this.checkBox51 = new Microsoft.Office.Tools.Word.Controls.CheckBox(Globals.Factory, this.ItemProvider, this.HostContext, "53DD5281F5D08E54284587445713A5F40399D5", "53DD5281F5D08E54284587445713A5F40399D5", this, "checkBox51");
            this.checkBox52 = new Microsoft.Office.Tools.Word.Controls.CheckBox(Globals.Factory, this.ItemProvider, this.HostContext, "579769FF45062354C765B643558E35C747AE35", "579769FF45062354C765B643558E35C747AE35", this, "checkBox52");
            this.checkBox53 = new Microsoft.Office.Tools.Word.Controls.CheckBox(Globals.Factory, this.ItemProvider, this.HostContext, "54AABC8D7532BD543005B5EA553C46607EAB05", "54AABC8D7532BD543005B5EA553C46607EAB05", this, "checkBox53");
            this.checkBox54 = new Microsoft.Office.Tools.Word.Controls.CheckBox(Globals.Factory, this.ItemProvider, this.HostContext, "5F0F3682D56E8F5465C596AC511BE1AF003EC5", "5F0F3682D56E8F5465C596AC511BE1AF003EC5", this, "checkBox54");
            this.checkBox55 = new Microsoft.Office.Tools.Word.Controls.CheckBox(Globals.Factory, this.ItemProvider, this.HostContext, "5BB9D572B546A954D995B8325CE899C6930C65", "5BB9D572B546A954D995B8325CE899C6930C65", this, "checkBox55");
            this.checkBox56 = new Microsoft.Office.Tools.Word.Controls.CheckBox(Globals.Factory, this.ItemProvider, this.HostContext, "51DED6EC852687541355B26657D38BB837F7C5", "51DED6EC852687541355B26657D38BB837F7C5", this, "checkBox56");
            this.checkBox57 = new Microsoft.Office.Tools.Word.Controls.CheckBox(Globals.Factory, this.ItemProvider, this.HostContext, "54C1762845F00D54D1D5B280592945524911E5", "54C1762845F00D54D1D5B280592945524911E5", this, "checkBox57");
            this.checkBox58 = new Microsoft.Office.Tools.Word.Controls.CheckBox(Globals.Factory, this.ItemProvider, this.HostContext, "5C607B6E855609540675893D5C0310F977FCC5", "5C607B6E855609540675893D5C0310F977FCC5", this, "checkBox58");
            this.checkBox59 = new Microsoft.Office.Tools.Word.Controls.CheckBox(Globals.Factory, this.ItemProvider, this.HostContext, "5552E99E95D65054EFD595E25156576403F2F5", "5552E99E95D65054EFD595E25156576403F2F5", this, "checkBox59");
            this.checkBox62 = new Microsoft.Office.Tools.Word.Controls.CheckBox(Globals.Factory, this.ItemProvider, this.HostContext, "594F620135092E5437A5B4E45A22A8709D8195", "594F620135092E5437A5B4E45A22A8709D8195", this, "checkBox62");
            this.checkBox60 = new Microsoft.Office.Tools.Word.Controls.CheckBox(Globals.Factory, this.ItemProvider, this.HostContext, "67FA2B1366E419641266AAE564C2883D331316", "67FA2B1366E419641266AAE564C2883D331316", this, "checkBox60");
            this.checkBox61 = new Microsoft.Office.Tools.Word.Controls.CheckBox(Globals.Factory, this.ItemProvider, this.HostContext, "68A35656F6CB1D6463769C1162E4DB12364ED6", "68A35656F6CB1D6463769C1162E4DB12364ED6", this, "checkBox61");
            this.checkBox63 = new Microsoft.Office.Tools.Word.Controls.CheckBox(Globals.Factory, this.ItemProvider, this.HostContext, "64C83AC0C695CE64FD0694F36F11FE666C69B6", "64C83AC0C695CE64FD0694F36F11FE666C69B6", this, "checkBox63");
            this.checkBox64 = new Microsoft.Office.Tools.Word.Controls.CheckBox(Globals.Factory, this.ItemProvider, this.HostContext, "6EDEF69E961C8964E226B8586A806696C9F156", "6EDEF69E961C8964E226B8586A806696C9F156", this, "checkBox64");
            this.checkBox65 = new Microsoft.Office.Tools.Word.Controls.CheckBox(Globals.Factory, this.ItemProvider, this.HostContext, "666DB36EA6FBE964A9B6807C6DD0E68D6E6D96", "666DB36EA6FBE964A9B6807C6DD0E68D6E6D96", this, "checkBox65");
            this.checkBox66 = new Microsoft.Office.Tools.Word.Controls.CheckBox(Globals.Factory, this.ItemProvider, this.HostContext, "616B89F1D62170644346AD5767ECBC7B862376", "616B89F1D62170644346AD5767ECBC7B862376", this, "checkBox66");
            this.checkBox67 = new Microsoft.Office.Tools.Word.Controls.CheckBox(Globals.Factory, this.ItemProvider, this.HostContext, "6E09108F3638F7648186A6A766E395ABBBABC6", "6E09108F3638F7648186A6A766E395ABBBABC6", this, "checkBox67");
            this.checkBox68 = new Microsoft.Office.Tools.Word.Controls.CheckBox(Globals.Factory, this.ItemProvider, this.HostContext, "6F9FFB295640E664C95689BF6D18825D43DFE6", "6F9FFB295640E664C95689BF6D18825D43DFE6", this, "checkBox68");
            this.checkBox69 = new Microsoft.Office.Tools.Word.Controls.CheckBox(Globals.Factory, this.ItemProvider, this.HostContext, "62F3DD89D6C82F64E676B88C6C8710987E9156", "62F3DD89D6C82F64E676B88C6C8710987E9156", this, "checkBox69");
            this.checkBox70 = new Microsoft.Office.Tools.Word.Controls.CheckBox(Globals.Factory, this.ItemProvider, this.HostContext, "638117A6066EC2648ED691A461A8554862CF56", "638117A6066EC2648ED691A461A8554862CF56", this, "checkBox70");
            this.checkBox71 = new Microsoft.Office.Tools.Word.Controls.CheckBox(Globals.Factory, this.ItemProvider, this.HostContext, "7A2CC81E57956A7425D7B7B17116ECD24E4657", "7A2CC81E57956A7425D7B7B17116ECD24E4657", this, "checkBox71");
            this.checkBox72 = new Microsoft.Office.Tools.Word.Controls.CheckBox(Globals.Factory, this.ItemProvider, this.HostContext, "7BAD2D07D7293274B1A788BF7125B2135A0AC7", "7BAD2D07D7293274B1A788BF7125B2135A0AC7", this, "checkBox72");
            this.checkBox73 = new Microsoft.Office.Tools.Word.Controls.CheckBox(Globals.Factory, this.ItemProvider, this.HostContext, "7937D99AD76ED3747D1780A17E6CE7E8E9AA07", "7937D99AD76ED3747D1780A17E6CE7E8E9AA07", this, "checkBox73");
            this.checkBox74 = new Microsoft.Office.Tools.Word.Controls.CheckBox(Globals.Factory, this.ItemProvider, this.HostContext, "7E08608237D4AD741407BFFF77164B917EF597", "7E08608237D4AD741407BFFF77164B917EF597", this, "checkBox74");
            this.checkBox75 = new Microsoft.Office.Tools.Word.Controls.CheckBox(Globals.Factory, this.ItemProvider, this.HostContext, "7E54AA0407ABAF74D977BE647D9F3B49FDECE7", "7E54AA0407ABAF74D977BE647D9F3B49FDECE7", this, "checkBox75");
            this.checkBox76 = new Microsoft.Office.Tools.Word.Controls.CheckBox(Globals.Factory, this.ItemProvider, this.HostContext, "7C7484C617B3507489D78FE276E0F6DA7E29F7", "7C7484C617B3507489D78FE276E0F6DA7E29F7", this, "checkBox76");
            this.checkBox77 = new Microsoft.Office.Tools.Word.Controls.CheckBox(Globals.Factory, this.ItemProvider, this.HostContext, "7E417C5DB7ED4B74E2B795427C8396C58162A7", "7E417C5DB7ED4B74E2B795427C8396C58162A7", this, "checkBox77");
            this.checkBox78 = new Microsoft.Office.Tools.Word.Controls.CheckBox(Globals.Factory, this.ItemProvider, this.HostContext, "770E55EB87E28B744127BB867EF03643B77767", "770E55EB87E28B744127BB867EF03643B77767", this, "checkBox78");
            this.checkBox79 = new Microsoft.Office.Tools.Word.Controls.CheckBox(Globals.Factory, this.ItemProvider, this.HostContext, "75BC8B82F7696C7486A7B3EB7AD97A129353A7", "75BC8B82F7696C7486A7B3EB7AD97A129353A7", this, "checkBox79");
            this.checkBox80 = new Microsoft.Office.Tools.Word.Controls.CheckBox(Globals.Factory, this.ItemProvider, this.HostContext, "7ED08AC1373554746237A15273C4AEE776D2E7", "7ED08AC1373554746237A15273C4AEE776D2E7", this, "checkBox80");
            this.checkBox81 = new Microsoft.Office.Tools.Word.Controls.CheckBox(Globals.Factory, this.ItemProvider, this.HostContext, "8EA708DBF8C71D8468C8A0FB878C31774B3788", "8EA708DBF8C71D8468C8A0FB878C31774B3788", this, "checkBox81");
            this.checkBox82 = new Microsoft.Office.Tools.Word.Controls.CheckBox(Globals.Factory, this.ItemProvider, this.HostContext, "8782C10FA83BC6842B38AC1382307493957318", "8782C10FA83BC6842B38AC1382307493957318", this, "checkBox82");
            this.checkBox83 = new Microsoft.Office.Tools.Word.Controls.CheckBox(Globals.Factory, this.ItemProvider, this.HostContext, "8FB25DBBB816A18419088BFB8AE4A26D5DD778", "8FB25DBBB816A18419088BFB8AE4A26D5DD778", this, "checkBox83");
            this.checkBox84 = new Microsoft.Office.Tools.Word.Controls.CheckBox(Globals.Factory, this.ItemProvider, this.HostContext, "84833469680CC184F95885AC8F2E2FBAF59B68", "84833469680CC184F95885AC8F2E2FBAF59B68", this, "checkBox84");
            this.checkBox85 = new Microsoft.Office.Tools.Word.Controls.CheckBox(Globals.Factory, this.ItemProvider, this.HostContext, "871BA74F58954C849F989A228B13097D2634F8", "871BA74F58954C849F989A228B13097D2634F8", this, "checkBox85");
            this.checkBox86 = new Microsoft.Office.Tools.Word.Controls.CheckBox(Globals.Factory, this.ItemProvider, this.HostContext, "8313134DC8128D843F68AE7780925489290338", "8313134DC8128D843F68AE7780925489290338", this, "checkBox86");
            this.checkBox87 = new Microsoft.Office.Tools.Word.Controls.CheckBox(Globals.Factory, this.ItemProvider, this.HostContext, "8D07C63658834984D62894898DC1CD96F1AD68", "8D07C63658834984D62894898DC1CD96F1AD68", this, "checkBox87");
            this.checkBox88 = new Microsoft.Office.Tools.Word.Controls.CheckBox(Globals.Factory, this.ItemProvider, this.HostContext, "82C2F6C098EBF8843ED88092818153039F1308", "82C2F6C098EBF8843ED88092818153039F1308", this, "checkBox88");
            this.checkBox89 = new Microsoft.Office.Tools.Word.Controls.CheckBox(Globals.Factory, this.ItemProvider, this.HostContext, "8D407A3DB80BE9840568BA97871B6399307E38", "8D407A3DB80BE9840568BA97871B6399307E38", this, "checkBox89");
            this.checkBox90 = new Microsoft.Office.Tools.Word.Controls.CheckBox(Globals.Factory, this.ItemProvider, this.HostContext, "8EA858AAC8D94B845C18A6BC82A01DB0840608", "8EA858AAC8D94B845C18A6BC82A01DB0840608", this, "checkBox90");
            this.checkBox91 = new Microsoft.Office.Tools.Word.Controls.CheckBox(Globals.Factory, this.ItemProvider, this.HostContext, "90441936C92E81949479881593237396527E69", "90441936C92E81949479881593237396527E69", this, "checkBox91");
            this.checkBox92 = new Microsoft.Office.Tools.Word.Controls.CheckBox(Globals.Factory, this.ItemProvider, this.HostContext, "904B2DAD69D6A4948A498A3B9D5FF24EEB6569", "904B2DAD69D6A4948A498A3B9D5FF24EEB6569", this, "checkBox92");
            this.checkBox93 = new Microsoft.Office.Tools.Word.Controls.CheckBox(Globals.Factory, this.ItemProvider, this.HostContext, "947A8337F96DEA949499AC31952AD0F77442F9", "947A8337F96DEA949499AC31952AD0F77442F9", this, "checkBox93");
            this.checkBox94 = new Microsoft.Office.Tools.Word.Controls.CheckBox(Globals.Factory, this.ItemProvider, this.HostContext, "9D3C433B9941DA9419C986579F8A07F8122769", "9D3C433B9941DA9419C986579F8A07F8122769", this, "checkBox94");
            this.checkBox95 = new Microsoft.Office.Tools.Word.Controls.CheckBox(Globals.Factory, this.ItemProvider, this.HostContext, "916FE27EB9D60494BAF98536913F54F4E6AA59", "916FE27EB9D60494BAF98536913F54F4E6AA59", this, "checkBox95");
            this.checkBox96 = new Microsoft.Office.Tools.Word.Controls.CheckBox(Globals.Factory, this.ItemProvider, this.HostContext, "9D1ECB2AD9445594B139B52B9B24BB786E0529", "9D1ECB2AD9445594B139B52B9B24BB786E0529", this, "checkBox96");
            this.btnGerarXML = new Microsoft.Office.Tools.Word.Controls.Button(Globals.Factory, this.ItemProvider, this.HostContext, "9160FE7129F587942FC996799B9C295D26C8B9", "9160FE7129F587942FC996799B9C295D26C8B9", this, "btnGerarXML");
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "15.0.0.0")]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void InitializeComponents() {
            // 
            // checkBox01
            // 
            this.checkBox01.Name = "checkBox01";
            // 
            // checkBox02
            // 
            this.checkBox02.Name = "checkBox02";
            // 
            // checkBox03
            // 
            this.checkBox03.Name = "checkBox03";
            // 
            // checkBox04
            // 
            this.checkBox04.Name = "checkBox04";
            // 
            // checkBox05
            // 
            this.checkBox05.Name = "checkBox05";
            // 
            // checkBox06
            // 
            this.checkBox06.Name = "checkBox06";
            // 
            // checkBox07
            // 
            this.checkBox07.Name = "checkBox07";
            // 
            // checkBox08
            // 
            this.checkBox08.Name = "checkBox08";
            // 
            // checkBox09
            // 
            this.checkBox09.Name = "checkBox09";
            // 
            // checkBox10
            // 
            this.checkBox10.Name = "checkBox10";
            // 
            // checkBox11
            // 
            this.checkBox11.Name = "checkBox11";
            // 
            // checkBox12
            // 
            this.checkBox12.Name = "checkBox12";
            // 
            // checkBox13
            // 
            this.checkBox13.Name = "checkBox13";
            // 
            // checkBox14
            // 
            this.checkBox14.Name = "checkBox14";
            // 
            // checkBox15
            // 
            this.checkBox15.Name = "checkBox15";
            // 
            // checkBox16
            // 
            this.checkBox16.Name = "checkBox16";
            // 
            // checkBox17
            // 
            this.checkBox17.Name = "checkBox17";
            // 
            // checkBox18
            // 
            this.checkBox18.Name = "checkBox18";
            // 
            // checkBox19
            // 
            this.checkBox19.Name = "checkBox19";
            // 
            // checkBox20
            // 
            this.checkBox20.Name = "checkBox20";
            // 
            // checkBox21
            // 
            this.checkBox21.Name = "checkBox21";
            // 
            // checkBox22
            // 
            this.checkBox22.Name = "checkBox22";
            // 
            // checkBox23
            // 
            this.checkBox23.Name = "checkBox23";
            // 
            // checkBox24
            // 
            this.checkBox24.Name = "checkBox24";
            // 
            // checkBox25
            // 
            this.checkBox25.Name = "checkBox25";
            // 
            // checkBox26
            // 
            this.checkBox26.Name = "checkBox26";
            // 
            // checkBox29
            // 
            this.checkBox29.Name = "checkBox29";
            // 
            // checkBox28
            // 
            this.checkBox28.Name = "checkBox28";
            // 
            // checkBox27
            // 
            this.checkBox27.Name = "checkBox27";
            // 
            // checkBox30
            // 
            this.checkBox30.Name = "checkBox30";
            // 
            // checkBox31
            // 
            this.checkBox31.Name = "checkBox31";
            // 
            // checkBox32
            // 
            this.checkBox32.Name = "checkBox32";
            // 
            // checkBox38
            // 
            this.checkBox38.Name = "checkBox38";
            // 
            // checkBox37
            // 
            this.checkBox37.Name = "checkBox37";
            // 
            // checkBox36
            // 
            this.checkBox36.Name = "checkBox36";
            // 
            // checkBox35
            // 
            this.checkBox35.Name = "checkBox35";
            // 
            // checkBox34
            // 
            this.checkBox34.Name = "checkBox34";
            // 
            // checkBox33
            // 
            this.checkBox33.Name = "checkBox33";
            // 
            // checkBox39
            // 
            this.checkBox39.Name = "checkBox39";
            // 
            // checkBox40
            // 
            this.checkBox40.Name = "checkBox40";
            // 
            // checkBox41
            // 
            this.checkBox41.Name = "checkBox41";
            // 
            // checkBox42
            // 
            this.checkBox42.Name = "checkBox42";
            // 
            // checkBox43
            // 
            this.checkBox43.Name = "checkBox43";
            // 
            // checkBox44
            // 
            this.checkBox44.Name = "checkBox44";
            // 
            // checkBox45
            // 
            this.checkBox45.Name = "checkBox45";
            // 
            // checkBox46
            // 
            this.checkBox46.Name = "checkBox46";
            // 
            // checkBox47
            // 
            this.checkBox47.Name = "checkBox47";
            // 
            // checkBox48
            // 
            this.checkBox48.Name = "checkBox48";
            // 
            // checkBox49
            // 
            this.checkBox49.Name = "checkBox49";
            // 
            // checkBox50
            // 
            this.checkBox50.Name = "checkBox50";
            // 
            // checkBox51
            // 
            this.checkBox51.Name = "checkBox51";
            // 
            // checkBox52
            // 
            this.checkBox52.Name = "checkBox52";
            // 
            // checkBox53
            // 
            this.checkBox53.Name = "checkBox53";
            // 
            // checkBox54
            // 
            this.checkBox54.Name = "checkBox54";
            // 
            // checkBox55
            // 
            this.checkBox55.Name = "checkBox55";
            // 
            // checkBox56
            // 
            this.checkBox56.Name = "checkBox56";
            // 
            // checkBox57
            // 
            this.checkBox57.Name = "checkBox57";
            // 
            // checkBox58
            // 
            this.checkBox58.Name = "checkBox58";
            // 
            // checkBox59
            // 
            this.checkBox59.Name = "checkBox59";
            // 
            // checkBox62
            // 
            this.checkBox62.Name = "checkBox62";
            // 
            // checkBox60
            // 
            this.checkBox60.Name = "checkBox60";
            // 
            // checkBox61
            // 
            this.checkBox61.Name = "checkBox61";
            // 
            // checkBox63
            // 
            this.checkBox63.Name = "checkBox63";
            // 
            // checkBox64
            // 
            this.checkBox64.Name = "checkBox64";
            // 
            // checkBox65
            // 
            this.checkBox65.Name = "checkBox65";
            // 
            // checkBox66
            // 
            this.checkBox66.Name = "checkBox66";
            // 
            // checkBox67
            // 
            this.checkBox67.Name = "checkBox67";
            // 
            // checkBox68
            // 
            this.checkBox68.Name = "checkBox68";
            // 
            // checkBox69
            // 
            this.checkBox69.Name = "checkBox69";
            // 
            // checkBox70
            // 
            this.checkBox70.Name = "checkBox70";
            // 
            // checkBox71
            // 
            this.checkBox71.Name = "checkBox71";
            // 
            // checkBox72
            // 
            this.checkBox72.Name = "checkBox72";
            // 
            // checkBox73
            // 
            this.checkBox73.Name = "checkBox73";
            // 
            // checkBox74
            // 
            this.checkBox74.Name = "checkBox74";
            // 
            // checkBox75
            // 
            this.checkBox75.Name = "checkBox75";
            // 
            // checkBox76
            // 
            this.checkBox76.Name = "checkBox76";
            // 
            // checkBox77
            // 
            this.checkBox77.Name = "checkBox77";
            // 
            // checkBox78
            // 
            this.checkBox78.Name = "checkBox78";
            // 
            // checkBox79
            // 
            this.checkBox79.Name = "checkBox79";
            // 
            // checkBox80
            // 
            this.checkBox80.Name = "checkBox80";
            // 
            // checkBox81
            // 
            this.checkBox81.Name = "checkBox81";
            // 
            // checkBox82
            // 
            this.checkBox82.Name = "checkBox82";
            // 
            // checkBox83
            // 
            this.checkBox83.Name = "checkBox83";
            // 
            // checkBox84
            // 
            this.checkBox84.Name = "checkBox84";
            // 
            // checkBox85
            // 
            this.checkBox85.Name = "checkBox85";
            // 
            // checkBox86
            // 
            this.checkBox86.Name = "checkBox86";
            // 
            // checkBox87
            // 
            this.checkBox87.Name = "checkBox87";
            // 
            // checkBox88
            // 
            this.checkBox88.Name = "checkBox88";
            // 
            // checkBox89
            // 
            this.checkBox89.Name = "checkBox89";
            // 
            // checkBox90
            // 
            this.checkBox90.Name = "checkBox90";
            // 
            // checkBox91
            // 
            this.checkBox91.Name = "checkBox91";
            // 
            // checkBox92
            // 
            this.checkBox92.Name = "checkBox92";
            // 
            // checkBox93
            // 
            this.checkBox93.Name = "checkBox93";
            // 
            // checkBox94
            // 
            this.checkBox94.Name = "checkBox94";
            // 
            // checkBox95
            // 
            this.checkBox95.Name = "checkBox95";
            // 
            // checkBox96
            // 
            this.checkBox96.Name = "checkBox96";
            // 
            // ActionsPane
            // 
            this.ActionsPane.AutoSize = false;
            this.ActionsPane.AutoValidate = System.Windows.Forms.AutoValidate.EnablePreventFocusChange;
            // 
            // comboBoxContentControl1
            // 
            this.comboBoxContentControl1.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // datePickerContentControl1
            // 
            this.datePickerContentControl1.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // btnGerarXML
            // 
            this.btnGerarXML.BackColor = System.Drawing.SystemColors.Control;
            this.btnGerarXML.ForeColor = System.Drawing.SystemColors.ControlText;
            this.btnGerarXML.Name = "btnGerarXML";
            this.btnGerarXML.Text = "Gerar XML";
            this.btnGerarXML.UseVisualStyleBackColor = false;
            // 
            // ThisDocument
            // 
            this.checkBox01.BindingContext = this.BindingContext;
            this.checkBox02.BindingContext = this.BindingContext;
            this.checkBox03.BindingContext = this.BindingContext;
            this.checkBox04.BindingContext = this.BindingContext;
            this.checkBox05.BindingContext = this.BindingContext;
            this.checkBox06.BindingContext = this.BindingContext;
            this.checkBox07.BindingContext = this.BindingContext;
            this.checkBox08.BindingContext = this.BindingContext;
            this.checkBox09.BindingContext = this.BindingContext;
            this.checkBox10.BindingContext = this.BindingContext;
            this.checkBox11.BindingContext = this.BindingContext;
            this.checkBox12.BindingContext = this.BindingContext;
            this.checkBox13.BindingContext = this.BindingContext;
            this.checkBox14.BindingContext = this.BindingContext;
            this.checkBox15.BindingContext = this.BindingContext;
            this.checkBox16.BindingContext = this.BindingContext;
            this.checkBox17.BindingContext = this.BindingContext;
            this.checkBox18.BindingContext = this.BindingContext;
            this.checkBox19.BindingContext = this.BindingContext;
            this.checkBox20.BindingContext = this.BindingContext;
            this.checkBox21.BindingContext = this.BindingContext;
            this.checkBox22.BindingContext = this.BindingContext;
            this.checkBox23.BindingContext = this.BindingContext;
            this.checkBox24.BindingContext = this.BindingContext;
            this.checkBox25.BindingContext = this.BindingContext;
            this.checkBox26.BindingContext = this.BindingContext;
            this.checkBox29.BindingContext = this.BindingContext;
            this.checkBox28.BindingContext = this.BindingContext;
            this.checkBox27.BindingContext = this.BindingContext;
            this.checkBox30.BindingContext = this.BindingContext;
            this.checkBox31.BindingContext = this.BindingContext;
            this.checkBox32.BindingContext = this.BindingContext;
            this.checkBox38.BindingContext = this.BindingContext;
            this.checkBox37.BindingContext = this.BindingContext;
            this.checkBox36.BindingContext = this.BindingContext;
            this.checkBox35.BindingContext = this.BindingContext;
            this.checkBox34.BindingContext = this.BindingContext;
            this.checkBox33.BindingContext = this.BindingContext;
            this.checkBox39.BindingContext = this.BindingContext;
            this.checkBox40.BindingContext = this.BindingContext;
            this.checkBox41.BindingContext = this.BindingContext;
            this.checkBox42.BindingContext = this.BindingContext;
            this.checkBox43.BindingContext = this.BindingContext;
            this.checkBox44.BindingContext = this.BindingContext;
            this.checkBox45.BindingContext = this.BindingContext;
            this.checkBox46.BindingContext = this.BindingContext;
            this.checkBox47.BindingContext = this.BindingContext;
            this.checkBox48.BindingContext = this.BindingContext;
            this.checkBox49.BindingContext = this.BindingContext;
            this.checkBox50.BindingContext = this.BindingContext;
            this.checkBox51.BindingContext = this.BindingContext;
            this.checkBox52.BindingContext = this.BindingContext;
            this.checkBox53.BindingContext = this.BindingContext;
            this.checkBox54.BindingContext = this.BindingContext;
            this.checkBox55.BindingContext = this.BindingContext;
            this.checkBox56.BindingContext = this.BindingContext;
            this.checkBox57.BindingContext = this.BindingContext;
            this.checkBox58.BindingContext = this.BindingContext;
            this.checkBox59.BindingContext = this.BindingContext;
            this.checkBox62.BindingContext = this.BindingContext;
            this.checkBox60.BindingContext = this.BindingContext;
            this.checkBox61.BindingContext = this.BindingContext;
            this.checkBox63.BindingContext = this.BindingContext;
            this.checkBox64.BindingContext = this.BindingContext;
            this.checkBox65.BindingContext = this.BindingContext;
            this.checkBox66.BindingContext = this.BindingContext;
            this.checkBox67.BindingContext = this.BindingContext;
            this.checkBox68.BindingContext = this.BindingContext;
            this.checkBox69.BindingContext = this.BindingContext;
            this.checkBox70.BindingContext = this.BindingContext;
            this.checkBox71.BindingContext = this.BindingContext;
            this.checkBox72.BindingContext = this.BindingContext;
            this.checkBox73.BindingContext = this.BindingContext;
            this.checkBox74.BindingContext = this.BindingContext;
            this.checkBox75.BindingContext = this.BindingContext;
            this.checkBox76.BindingContext = this.BindingContext;
            this.checkBox77.BindingContext = this.BindingContext;
            this.checkBox78.BindingContext = this.BindingContext;
            this.checkBox79.BindingContext = this.BindingContext;
            this.checkBox80.BindingContext = this.BindingContext;
            this.checkBox81.BindingContext = this.BindingContext;
            this.checkBox82.BindingContext = this.BindingContext;
            this.checkBox83.BindingContext = this.BindingContext;
            this.checkBox84.BindingContext = this.BindingContext;
            this.checkBox85.BindingContext = this.BindingContext;
            this.checkBox86.BindingContext = this.BindingContext;
            this.checkBox87.BindingContext = this.BindingContext;
            this.checkBox88.BindingContext = this.BindingContext;
            this.checkBox89.BindingContext = this.BindingContext;
            this.checkBox90.BindingContext = this.BindingContext;
            this.checkBox91.BindingContext = this.BindingContext;
            this.checkBox92.BindingContext = this.BindingContext;
            this.checkBox93.BindingContext = this.BindingContext;
            this.checkBox94.BindingContext = this.BindingContext;
            this.checkBox95.BindingContext = this.BindingContext;
            this.checkBox96.BindingContext = this.BindingContext;
            this.btnGerarXML.BindingContext = this.BindingContext;
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        private bool NeedsFill(string MemberName) {
            return this.DataHost.NeedsFill(this, MemberName);
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "15.0.0.0")]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        protected override void OnShutdown() {
            this.datePickerContentControl1.Dispose();
            this.comboBoxContentControl1.Dispose();
            this.ActionsPane.Dispose();
            base.OnShutdown();
        }
    }
    
    /// 
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "15.0.0.0")]
    internal sealed partial class Globals {
        
        /// 
        private Globals() {
        }
        
        private static ThisDocument _ThisDocument;
        
        private static global::Microsoft.Office.Tools.Word.Factory _factory;
        
        private static ThisRibbonCollection _ThisRibbonCollection;
        
        internal static ThisDocument ThisDocument {
            get {
                return _ThisDocument;
            }
            set {
                if ((_ThisDocument == null)) {
                    _ThisDocument = value;
                }
                else {
                    throw new System.NotSupportedException();
                }
            }
        }
        
        internal static global::Microsoft.Office.Tools.Word.Factory Factory {
            get {
                return _factory;
            }
            set {
                if ((_factory == null)) {
                    _factory = value;
                }
                else {
                    throw new System.NotSupportedException();
                }
            }
        }
        
        internal static ThisRibbonCollection Ribbons {
            get {
                if ((_ThisRibbonCollection == null)) {
                    _ThisRibbonCollection = new ThisRibbonCollection(_factory.GetRibbonFactory());
                }
                return _ThisRibbonCollection;
            }
        }
    }
    
    /// 
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "15.0.0.0")]
    internal sealed partial class ThisRibbonCollection : Microsoft.Office.Tools.Ribbon.RibbonCollectionBase {
        
        /// 
        internal ThisRibbonCollection(global::Microsoft.Office.Tools.Ribbon.RibbonFactory factory) : 
                base(factory) {
        }
    }
}
