//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

#pragma warning disable 414
namespace CheckListReport {
    
    
    /// 
    [Microsoft.VisualStudio.Tools.Applications.Runtime.StartupObjectAttribute(0)]
    [global::System.Security.Permissions.PermissionSetAttribute(global::System.Security.Permissions.SecurityAction.Demand, Name="FullTrust")]
    public sealed partial class ThisDocument : Microsoft.Office.Tools.Word.DocumentBase {
        
        internal Microsoft.Office.Tools.ActionsPane ActionsPane;
        
        internal Microsoft.Office.Tools.Word.ComboBoxContentControl comboBoxContentControl1;
        
        internal Microsoft.Office.Tools.Word.DatePickerContentControl datePickerContentControl1;
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "15.0.0.0")]
        private global::System.Object missing = global::System.Type.Missing;
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "15.0.0.0")]
        internal Microsoft.Office.Interop.Word.Application ThisApplication;
        
        internal Microsoft.Office.Tools.Word.Controls.Button btnGerarXML;
        
        internal Microsoft.Office.Tools.Word.Controls.CheckBox checkBox01;
        
        internal Microsoft.Office.Tools.Word.Controls.CheckBox checkBox02;
        
        internal Microsoft.Office.Tools.Word.Controls.CheckBox checkBox03;
        
        internal Microsoft.Office.Tools.Word.Controls.CheckBox checkBox04;
        
        internal Microsoft.Office.Tools.Word.Controls.CheckBox checkBox05;
        
        internal Microsoft.Office.Tools.Word.Controls.CheckBox checkBox06;
        
        internal Microsoft.Office.Tools.Word.Controls.CheckBox checkBox07;
        
        internal Microsoft.Office.Tools.Word.Controls.CheckBox checkBox08;
        
        internal Microsoft.Office.Tools.Word.Controls.CheckBox checkBox09;
        
        internal Microsoft.Office.Tools.Word.Controls.CheckBox checkBox10;
        
        internal Microsoft.Office.Tools.Word.Controls.CheckBox checkBox11;
        
        internal Microsoft.Office.Tools.Word.Controls.CheckBox checkBox12;
        
        internal Microsoft.Office.Tools.Word.Controls.CheckBox checkBox13;
        
        internal Microsoft.Office.Tools.Word.Controls.CheckBox checkBox14;
        
        internal Microsoft.Office.Tools.Word.Controls.CheckBox checkBox15;
        
        internal Microsoft.Office.Tools.Word.Controls.CheckBox checkBox16;
        
        internal Microsoft.Office.Tools.Word.Controls.CheckBox checkBox17;
        
        internal Microsoft.Office.Tools.Word.Controls.CheckBox checkBox18;
        
        internal Microsoft.Office.Tools.Word.Controls.CheckBox checkBox19;
        
        internal Microsoft.Office.Tools.Word.Controls.CheckBox checkBox20;
        
        internal Microsoft.Office.Tools.Word.Controls.CheckBox checkBox21;
        
        internal Microsoft.Office.Tools.Word.Controls.CheckBox checkBox22;
        
        internal Microsoft.Office.Tools.Word.Controls.CheckBox checkBox23;
        
        internal Microsoft.Office.Tools.Word.Controls.CheckBox checkBox24;
        
        internal Microsoft.Office.Tools.Word.Controls.CheckBox checkBox25;
        
        internal Microsoft.Office.Tools.Word.Controls.CheckBox checkBox26;
        
        internal Microsoft.Office.Tools.Word.Controls.CheckBox checkBox27;
        
        internal Microsoft.Office.Tools.Word.Controls.CheckBox checkBox28;
        
        internal Microsoft.Office.Tools.Word.Controls.CheckBox checkBox29;
        
        internal Microsoft.Office.Tools.Word.Controls.CheckBox checkBox30;
        
        internal Microsoft.Office.Tools.Word.Controls.CheckBox checkBox31;
        
        internal Microsoft.Office.Tools.Word.Controls.CheckBox checkBox32;
        
        internal Microsoft.Office.Tools.Word.Controls.CheckBox checkBox33;
        
        internal Microsoft.Office.Tools.Word.Controls.CheckBox checkBox34;
        
        internal Microsoft.Office.Tools.Word.Controls.CheckBox checkBox35;
        
        internal Microsoft.Office.Tools.Word.Controls.CheckBox checkBox36;
        
        internal Microsoft.Office.Tools.Word.Controls.CheckBox checkBox37;
        
        internal Microsoft.Office.Tools.Word.Controls.CheckBox checkBox38;
        
        internal Microsoft.Office.Tools.Word.Controls.CheckBox checkBox39;
        
        internal Microsoft.Office.Tools.Word.Controls.CheckBox checkBox40;
        
        internal Microsoft.Office.Tools.Word.Controls.CheckBox checkBox41;
        
        internal Microsoft.Office.Tools.Word.Controls.CheckBox checkBox42;
        
        internal Microsoft.Office.Tools.Word.Controls.CheckBox checkBox43;
        
        internal Microsoft.Office.Tools.Word.Controls.CheckBox checkBox44;
        
        internal Microsoft.Office.Tools.Word.Controls.CheckBox checkBox45;
        
        internal Microsoft.Office.Tools.Word.Controls.CheckBox checkBox48;
        
        internal Microsoft.Office.Tools.Word.Controls.CheckBox checkBox47;
        
        internal Microsoft.Office.Tools.Word.Controls.CheckBox checkBox46;
        
        internal Microsoft.Office.Tools.Word.Controls.CheckBox checkBox49;
        
        internal Microsoft.Office.Tools.Word.Controls.CheckBox checkBox50;
        
        internal Microsoft.Office.Tools.Word.Controls.CheckBox checkBox51;
        
        internal Microsoft.Office.Tools.Word.Controls.CheckBox checkBox52;
        
        internal Microsoft.Office.Tools.Word.Controls.CheckBox checkBox53;
        
        internal Microsoft.Office.Tools.Word.Controls.CheckBox checkBox54;
        
        internal Microsoft.Office.Tools.Word.Controls.CheckBox checkBox55;
        
        internal Microsoft.Office.Tools.Word.Controls.CheckBox checkBox56;
        
        internal Microsoft.Office.Tools.Word.Controls.CheckBox checkBox57;
        
        internal Microsoft.Office.Tools.Word.Controls.CheckBox checkBox58;
        
        internal Microsoft.Office.Tools.Word.Controls.CheckBox checkBox59;
        
        internal Microsoft.Office.Tools.Word.Controls.CheckBox checkBox60;
        
        internal Microsoft.Office.Tools.Word.Controls.CheckBox checkBox61;
        
        internal Microsoft.Office.Tools.Word.Controls.CheckBox checkBox62;
        
        internal Microsoft.Office.Tools.Word.Controls.CheckBox checkBox63;
        
        internal Microsoft.Office.Tools.Word.Controls.CheckBox checkBox64;
        
        internal Microsoft.Office.Tools.Word.Controls.CheckBox checkBox65;
        
        internal Microsoft.Office.Tools.Word.Controls.CheckBox checkBox66;
        
        internal Microsoft.Office.Tools.Word.Controls.CheckBox checkBox67;
        
        internal Microsoft.Office.Tools.Word.Controls.CheckBox checkBox68;
        
        internal Microsoft.Office.Tools.Word.Controls.CheckBox checkBox69;
        
        internal Microsoft.Office.Tools.Word.Controls.CheckBox checkBox70;
        
        internal Microsoft.Office.Tools.Word.Controls.CheckBox checkBox71;
        
        internal Microsoft.Office.Tools.Word.Controls.CheckBox checkBox72;
        
        internal Microsoft.Office.Tools.Word.Controls.CheckBox checkBox73;
        
        internal Microsoft.Office.Tools.Word.Controls.CheckBox checkBox74;
        
        internal Microsoft.Office.Tools.Word.Controls.CheckBox checkBox75;
        
        internal Microsoft.Office.Tools.Word.Controls.CheckBox checkBox76;
        
        internal Microsoft.Office.Tools.Word.Controls.CheckBox checkBox77;
        
        internal Microsoft.Office.Tools.Word.Controls.CheckBox checkBox78;
        
        internal Microsoft.Office.Tools.Word.Controls.CheckBox checkBox79;
        
        internal Microsoft.Office.Tools.Word.Controls.CheckBox checkBox80;
        
        internal Microsoft.Office.Tools.Word.Controls.CheckBox checkBox81;
        
        internal Microsoft.Office.Tools.Word.Controls.CheckBox checkBox82;
        
        internal Microsoft.Office.Tools.Word.Controls.CheckBox checkBox86;
        
        internal Microsoft.Office.Tools.Word.Controls.CheckBox checkBox87;
        
        internal Microsoft.Office.Tools.Word.Controls.CheckBox checkBox88;
        
        internal Microsoft.Office.Tools.Word.Controls.CheckBox checkBox89;
        
        internal Microsoft.Office.Tools.Word.Controls.CheckBox checkBox90;
        
        internal Microsoft.Office.Tools.Word.Controls.CheckBox checkBox91;
        
        internal Microsoft.Office.Tools.Word.Controls.CheckBox checkBox92;
        
        internal Microsoft.Office.Tools.Word.Controls.CheckBox checkBox93;
        
        internal Microsoft.Office.Tools.Word.Controls.CheckBox checkBox94;
        
        internal Microsoft.Office.Tools.Word.Controls.CheckBox checkBox95;
        
        internal Microsoft.Office.Tools.Word.Controls.CheckBox checkBox96;
        
        internal Microsoft.Office.Tools.Word.Controls.CheckBox checkBox83;
        
        internal Microsoft.Office.Tools.Word.Controls.CheckBox checkBox84;
        
        internal Microsoft.Office.Tools.Word.Controls.CheckBox checkBox85;
        
        internal Microsoft.Office.Tools.Word.Controls.CheckBox checkBox99;
        
        internal Microsoft.Office.Tools.Word.Controls.CheckBox checkBox98;
        
        internal Microsoft.Office.Tools.Word.Controls.CheckBox checkBox97;
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        public ThisDocument(global::Microsoft.Office.Tools.Word.Factory factory, global::System.IServiceProvider serviceProvider) : 
                base(factory, serviceProvider, "ThisDocument", "ThisDocument") {
            Globals.Factory = factory;
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "15.0.0.0")]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        protected override void Initialize() {
            base.Initialize();
            this.ThisApplication = this.GetHostItem<Microsoft.Office.Interop.Word.Application>(typeof(Microsoft.Office.Interop.Word.Application), "Application");
            Globals.ThisDocument = this;
            global::System.Windows.Forms.Application.EnableVisualStyles();
            this.InitializeCachedData();
            this.InitializeControls();
            this.InitializeComponents();
            this.InitializeData();
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "15.0.0.0")]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        protected override void FinishInitialization() {
            this.InternalStartup();
            this.OnStartup();
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "15.0.0.0")]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        protected override void InitializeDataBindings() {
            this.BeginInitialization();
            this.BindToData();
            this.EndInitialization();
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "15.0.0.0")]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void InitializeCachedData() {
            if ((this.DataHost == null)) {
                return;
            }
            if (this.DataHost.IsCacheInitialized) {
                this.DataHost.FillCachedData(this);
            }
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "15.0.0.0")]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void InitializeData() {
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "15.0.0.0")]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void BindToData() {
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        private void StartCaching(string MemberName) {
            this.DataHost.StartCaching(this, MemberName);
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        private void StopCaching(string MemberName) {
            this.DataHost.StopCaching(this, MemberName);
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        private bool IsCached(string MemberName) {
            return this.DataHost.IsCached(this, MemberName);
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "15.0.0.0")]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void BeginInitialization() {
            this.BeginInit();
            this.ActionsPane.BeginInit();
            this.comboBoxContentControl1.BeginInit();
            this.datePickerContentControl1.BeginInit();
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "15.0.0.0")]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void EndInitialization() {
            this.datePickerContentControl1.EndInit();
            this.comboBoxContentControl1.EndInit();
            this.ActionsPane.EndInit();
            this.EndInit();
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "15.0.0.0")]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void InitializeControls() {
            this.ActionsPane = Globals.Factory.CreateActionsPane(null, null, "ActionsPane", "ActionsPane", this);
            this.comboBoxContentControl1 = Globals.Factory.CreateComboBoxContentControl(null, null, "2897304870", "comboBoxContentControl1", this);
            this.datePickerContentControl1 = Globals.Factory.CreateDatePickerContentControl(null, null, "4179056737", "datePickerContentControl1", this);
            this.btnGerarXML = new Microsoft.Office.Tools.Word.Controls.Button(Globals.Factory, this.ItemProvider, this.HostContext, "78279A5477C890747D9786B87D8F14A4FFEBD7", "78279A5477C890747D9786B87D8F14A4FFEBD7", this, "btnGerarXML");
            this.checkBox01 = new Microsoft.Office.Tools.Word.Controls.CheckBox(Globals.Factory, this.ItemProvider, this.HostContext, "0EAA5CE7106279049730BB630331F8E0B36D00", "0EAA5CE7106279049730BB630331F8E0B36D00", this, "checkBox01");
            this.checkBox02 = new Microsoft.Office.Tools.Word.Controls.CheckBox(Globals.Factory, this.ItemProvider, this.HostContext, "1DA695D73156941454F1955911FAD7A1DA3F31", "1DA695D73156941454F1955911FAD7A1DA3F31", this, "checkBox02");
            this.checkBox03 = new Microsoft.Office.Tools.Word.Controls.CheckBox(Globals.Factory, this.ItemProvider, this.HostContext, "2E8C59F6A287CE248062B98323DC1FB5BED302", "2E8C59F6A287CE248062B98323DC1FB5BED302", this, "checkBox03");
            this.checkBox04 = new Microsoft.Office.Tools.Word.Controls.CheckBox(Globals.Factory, this.ItemProvider, this.HostContext, "37A544FFA35A0F347603AC093F5F0F829F09F3", "37A544FFA35A0F347603AC093F5F0F829F09F3", this, "checkBox04");
            this.checkBox05 = new Microsoft.Office.Tools.Word.Controls.CheckBox(Globals.Factory, this.ItemProvider, this.HostContext, "4A354B05D48D70442574AD144B80CA95909284", "4A354B05D48D70442574AD144B80CA95909284", this, "checkBox05");
            this.checkBox06 = new Microsoft.Office.Tools.Word.Controls.CheckBox(Globals.Factory, this.ItemProvider, this.HostContext, "5AB1990695482554229588B256588039C7E205", "5AB1990695482554229588B256588039C7E205", this, "checkBox06");
            this.checkBox07 = new Microsoft.Office.Tools.Word.Controls.CheckBox(Globals.Factory, this.ItemProvider, this.HostContext, "6C3B7B7BC6F7486484E6BAAC6AC87D52131E06", "6C3B7B7BC6F7486484E6BAAC6AC87D52131E06", this, "checkBox07");
            this.checkBox08 = new Microsoft.Office.Tools.Word.Controls.CheckBox(Globals.Factory, this.ItemProvider, this.HostContext, "74E97E8997A66D7413378291739FDCFE9D7167", "74E97E8997A66D7413378291739FDCFE9D7167", this, "checkBox08");
            this.checkBox09 = new Microsoft.Office.Tools.Word.Controls.CheckBox(Globals.Factory, this.ItemProvider, this.HostContext, "846CDEBF08843984C868808587D46B80876E18", "846CDEBF08843984C868808587D46B80876E18", this, "checkBox09");
            this.checkBox10 = new Microsoft.Office.Tools.Word.Controls.CheckBox(Globals.Factory, this.ItemProvider, this.HostContext, "9EB34EAE6910EA94EA09A7E19E8650E8944C09", "9EB34EAE6910EA94EA09A7E19E8650E8944C09", this, "checkBox10");
            this.checkBox11 = new Microsoft.Office.Tools.Word.Controls.CheckBox(Globals.Factory, this.ItemProvider, this.HostContext, "1C79D9EE61F8B0149FC1AE061AE124DFB91501", "1C79D9EE61F8B0149FC1AE061AE124DFB91501", this, "checkBox11");
            this.checkBox12 = new Microsoft.Office.Tools.Word.Controls.CheckBox(Globals.Factory, this.ItemProvider, this.HostContext, "12CA093541A996140B31A3B4117668AFA21761", "12CA093541A996140B31A3B4117668AFA21761", this, "checkBox12");
            this.checkBox13 = new Microsoft.Office.Tools.Word.Controls.CheckBox(Globals.Factory, this.ItemProvider, this.HostContext, "1A085661B1ACA714694193551BA3E425272891", "1A085661B1ACA714694193551BA3E425272891", this, "checkBox13");
            this.checkBox14 = new Microsoft.Office.Tools.Word.Controls.CheckBox(Globals.Factory, this.ItemProvider, this.HostContext, "1176DB46913566149681BFCC1459D520326441", "1176DB46913566149681BFCC1459D520326441", this, "checkBox14");
            this.checkBox15 = new Microsoft.Office.Tools.Word.Controls.CheckBox(Globals.Factory, this.ItemProvider, this.HostContext, "10CD1C0281B23014E921B4111965FEB2BCC881", "10CD1C0281B23014E921B4111965FEB2BCC881", this, "checkBox15");
            this.checkBox16 = new Microsoft.Office.Tools.Word.Controls.CheckBox(Globals.Factory, this.ItemProvider, this.HostContext, "1EACB54B61A45E1475518AE71970291968CC01", "1EACB54B61A45E1475518AE71970291968CC01", this, "checkBox16");
            this.checkBox17 = new Microsoft.Office.Tools.Word.Controls.CheckBox(Globals.Factory, this.ItemProvider, this.HostContext, "18F3359571D391144841B5181E4D91351C0731", "18F3359571D391144841B5181E4D91351C0731", this, "checkBox17");
            this.checkBox18 = new Microsoft.Office.Tools.Word.Controls.CheckBox(Globals.Factory, this.ItemProvider, this.HostContext, "1D007570D18643149AD1857E13DB6D5E7C60D1", "1D007570D18643149AD1857E13DB6D5E7C60D1", this, "checkBox18");
            this.checkBox19 = new Microsoft.Office.Tools.Word.Controls.CheckBox(Globals.Factory, this.ItemProvider, this.HostContext, "1918DBC221932714FD21B8DC1643B7F11E9841", "1918DBC221932714FD21B8DC1643B7F11E9841", this, "checkBox19");
            this.checkBox20 = new Microsoft.Office.Tools.Word.Controls.CheckBox(Globals.Factory, this.ItemProvider, this.HostContext, "10B26E1E112B7114FD418F0A1FD613C5E41771", "10B26E1E112B7114FD418F0A1FD613C5E41771", this, "checkBox20");
            this.checkBox21 = new Microsoft.Office.Tools.Word.Controls.CheckBox(Globals.Factory, this.ItemProvider, this.HostContext, "2D2613A8F2FD77247352A4BC2D2FD2527E6F62", "2D2613A8F2FD77247352A4BC2D2FD2527E6F62", this, "checkBox21");
            this.checkBox22 = new Microsoft.Office.Tools.Word.Controls.CheckBox(Globals.Factory, this.ItemProvider, this.HostContext, "265C1FC9D27B30241892B41E2C7DAB008CB252", "265C1FC9D27B30241892B41E2C7DAB008CB252", this, "checkBox22");
            this.checkBox23 = new Microsoft.Office.Tools.Word.Controls.CheckBox(Globals.Factory, this.ItemProvider, this.HostContext, "2AA7532D722B9824ECA2A68D29CDEBEB5C2B22", "2AA7532D722B9824ECA2A68D29CDEBEB5C2B22", this, "checkBox23");
            this.checkBox24 = new Microsoft.Office.Tools.Word.Controls.CheckBox(Globals.Factory, this.ItemProvider, this.HostContext, "2503F85E429779242EC29EAD2B4487E38BB6A2", "2503F85E429779242EC29EAD2B4487E38BB6A2", this, "checkBox24");
            this.checkBox25 = new Microsoft.Office.Tools.Word.Controls.CheckBox(Globals.Factory, this.ItemProvider, this.HostContext, "2887CEC09222AE245FC2B50D2E5DA5181F7472", "2887CEC09222AE245FC2B50D2E5DA5181F7472", this, "checkBox25");
            this.checkBox26 = new Microsoft.Office.Tools.Word.Controls.CheckBox(Globals.Factory, this.ItemProvider, this.HostContext, "2246266CE27999246452B6052D5D9741E56482", "2246266CE27999246452B6052D5D9741E56482", this, "checkBox26");
            this.checkBox27 = new Microsoft.Office.Tools.Word.Controls.CheckBox(Globals.Factory, this.ItemProvider, this.HostContext, "209DD028F265BC24B3D2B5D629744E7AECFC72", "209DD028F265BC24B3D2B5D629744E7AECFC72", this, "checkBox27");
            this.checkBox28 = new Microsoft.Office.Tools.Word.Controls.CheckBox(Globals.Factory, this.ItemProvider, this.HostContext, "22E8DFC30213E1246602A31C2FE685727BFD02", "22E8DFC30213E1246602A31C2FE685727BFD02", this, "checkBox28");
            this.checkBox29 = new Microsoft.Office.Tools.Word.Controls.CheckBox(Globals.Factory, this.ItemProvider, this.HostContext, "262879EB72AFB324A1D28CC42C8E78ACD34A92", "262879EB72AFB324A1D28CC42C8E78ACD34A92", this, "checkBox29");
            this.checkBox30 = new Microsoft.Office.Tools.Word.Controls.CheckBox(Globals.Factory, this.ItemProvider, this.HostContext, "246C8ED03202D724DDD29DCF216179AD0528E2", "246C8ED03202D724DDD29DCF216179AD0528E2", this, "checkBox30");
            this.checkBox31 = new Microsoft.Office.Tools.Word.Controls.CheckBox(Globals.Factory, this.ItemProvider, this.HostContext, "34BDDDDF13BAC634FD63AE2D36870F22415323", "34BDDDDF13BAC634FD63AE2D36870F22415323", this, "checkBox31");
            this.checkBox32 = new Microsoft.Office.Tools.Word.Controls.CheckBox(Globals.Factory, this.ItemProvider, this.HostContext, "30991338F3C4283479A3BAC73CCD88F266EC23", "30991338F3C4283479A3BAC73CCD88F266EC23", this, "checkBox32");
            this.checkBox33 = new Microsoft.Office.Tools.Word.Controls.CheckBox(Globals.Factory, this.ItemProvider, this.HostContext, "3F09820AB3768D345B13B3903D176F389B6AD3", "3F09820AB3768D345B13B3903D176F389B6AD3", this, "checkBox33");
            this.checkBox34 = new Microsoft.Office.Tools.Word.Controls.CheckBox(Globals.Factory, this.ItemProvider, this.HostContext, "344CD1F26338BF3427A38CEF3526B990849903", "344CD1F26338BF3427A38CEF3526B990849903", this, "checkBox34");
            this.checkBox35 = new Microsoft.Office.Tools.Word.Controls.CheckBox(Globals.Factory, this.ItemProvider, this.HostContext, "3BBA98E5F3161334E8B3AE5C3DCAB97B4477A3", "3BBA98E5F3161334E8B3AE5C3DCAB97B4477A3", this, "checkBox35");
            this.checkBox36 = new Microsoft.Office.Tools.Word.Controls.CheckBox(Globals.Factory, this.ItemProvider, this.HostContext, "36A20C48A3EB6834C97385EF33D522AEE38EE3", "36A20C48A3EB6834C97385EF33D522AEE38EE3", this, "checkBox36");
            this.checkBox37 = new Microsoft.Office.Tools.Word.Controls.CheckBox(Globals.Factory, this.ItemProvider, this.HostContext, "3C997BA3E38D143406F3A63B340C34D2DD5903", "3C997BA3E38D143406F3A63B340C34D2DD5903", this, "checkBox37");
            this.checkBox38 = new Microsoft.Office.Tools.Word.Controls.CheckBox(Globals.Factory, this.ItemProvider, this.HostContext, "3BCFA55E9320E43487938EC6387101FAB884B3", "3BCFA55E9320E43487938EC6387101FAB884B3", this, "checkBox38");
            this.checkBox39 = new Microsoft.Office.Tools.Word.Controls.CheckBox(Globals.Factory, this.ItemProvider, this.HostContext, "3E4AFC37E3E7CE345643805432D85683891B83", "3E4AFC37E3E7CE345643805432D85683891B83", this, "checkBox39");
            this.checkBox40 = new Microsoft.Office.Tools.Word.Controls.CheckBox(Globals.Factory, this.ItemProvider, this.HostContext, "332ECD28F32D88341ED3A2CC3D5F0FBAB848A3", "332ECD28F32D88341ED3A2CC3D5F0FBAB848A3", this, "checkBox40");
            this.checkBox41 = new Microsoft.Office.Tools.Word.Controls.CheckBox(Globals.Factory, this.ItemProvider, this.HostContext, "47CAC0FBB4CEE24469C4874B4EEE7C321AE654", "47CAC0FBB4CEE24469C4874B4EEE7C321AE654", this, "checkBox41");
            this.checkBox42 = new Microsoft.Office.Tools.Word.Controls.CheckBox(Globals.Factory, this.ItemProvider, this.HostContext, "47DBE8E2C4D8D444D1D49BE24D44E0B048AEE4", "47DBE8E2C4D8D444D1D49BE24D44E0B048AEE4", this, "checkBox42");
            this.checkBox43 = new Microsoft.Office.Tools.Word.Controls.CheckBox(Globals.Factory, this.ItemProvider, this.HostContext, "4E447355D466A3448ED4879F41D06D8697A954", "4E447355D466A3448ED4879F41D06D8697A954", this, "checkBox43");
            this.checkBox44 = new Microsoft.Office.Tools.Word.Controls.CheckBox(Globals.Factory, this.ItemProvider, this.HostContext, "472891D254799F44F4648CB846803EBA92C6B4", "472891D254799F44F4648CB846803EBA92C6B4", this, "checkBox44");
            this.checkBox45 = new Microsoft.Office.Tools.Word.Controls.CheckBox(Globals.Factory, this.ItemProvider, this.HostContext, "43E772BF64C359442024880D4DF0BA9F4ACCB4", "43E772BF64C359442024880D4DF0BA9F4ACCB4", this, "checkBox45");
            this.checkBox48 = new Microsoft.Office.Tools.Word.Controls.CheckBox(Globals.Factory, this.ItemProvider, this.HostContext, "49750F2544C3DB443454B1334E8E8B8FE98F34", "49750F2544C3DB443454B1334E8E8B8FE98F34", this, "checkBox48");
            this.checkBox47 = new Microsoft.Office.Tools.Word.Controls.CheckBox(Globals.Factory, this.ItemProvider, this.HostContext, "4B477FF8149E3C445C54B7624C6AC1895DD164", "4B477FF8149E3C445C54B7624C6AC1895DD164", this, "checkBox47");
            this.checkBox46 = new Microsoft.Office.Tools.Word.Controls.CheckBox(Globals.Factory, this.ItemProvider, this.HostContext, "45659F6BF4F8E9445FD4B50445021E7819D2A4", "45659F6BF4F8E9445FD4B50445021E7819D2A4", this, "checkBox46");
            this.checkBox49 = new Microsoft.Office.Tools.Word.Controls.CheckBox(Globals.Factory, this.ItemProvider, this.HostContext, "46F71AB844C4B344C3E4A7E34EC6D1D6541C34", "46F71AB844C4B344C3E4A7E34EC6D1D6541C34", this, "checkBox49");
            this.checkBox50 = new Microsoft.Office.Tools.Word.Controls.CheckBox(Globals.Factory, this.ItemProvider, this.HostContext, "44551B09F48B8D44A6A49B514AB69C5F3A70A4", "44551B09F48B8D44A6A49B514AB69C5F3A70A4", this, "checkBox50");
            this.checkBox51 = new Microsoft.Office.Tools.Word.Controls.CheckBox(Globals.Factory, this.ItemProvider, this.HostContext, "5220266D95D194546A35A32853DE94B8DFE545", "5220266D95D194546A35A32853DE94B8DFE545", this, "checkBox51");
            this.checkBox52 = new Microsoft.Office.Tools.Word.Controls.CheckBox(Globals.Factory, this.ItemProvider, this.HostContext, "5B6B3C4505B9A85405E5AFE355564F00AD1645", "5B6B3C4505B9A85405E5AFE355564F00AD1645", this, "checkBox52");
            this.checkBox53 = new Microsoft.Office.Tools.Word.Controls.CheckBox(Globals.Factory, this.ItemProvider, this.HostContext, "5745561935E9D5542505A5AD5E84DCB4A9C035", "5745561935E9D5542505A5AD5E84DCB4A9C035", this, "checkBox53");
            this.checkBox54 = new Microsoft.Office.Tools.Word.Controls.CheckBox(Globals.Factory, this.ItemProvider, this.HostContext, "5739AB19750D6A54C565AF0356D273BFD6A955", "5739AB19750D6A54C565AF0356D273BFD6A955", this, "checkBox54");
            this.checkBox55 = new Microsoft.Office.Tools.Word.Controls.CheckBox(Globals.Factory, this.ItemProvider, this.HostContext, "5968718C952DE1541635A66F532B2F2F412525", "5968718C952DE1541635A66F532B2F2F412525", this, "checkBox55");
            this.checkBox56 = new Microsoft.Office.Tools.Word.Controls.CheckBox(Globals.Factory, this.ItemProvider, this.HostContext, "52BA951755C35D54BE5597EF5EBFEABC784E55", "52BA951755C35D54BE5597EF5EBFEABC784E55", this, "checkBox56");
            this.checkBox57 = new Microsoft.Office.Tools.Word.Controls.CheckBox(Globals.Factory, this.ItemProvider, this.HostContext, "557FBA6DF59BE354C60595BE559DF4336B84B5", "557FBA6DF59BE354C60595BE559DF4336B84B5", this, "checkBox57");
            this.checkBox58 = new Microsoft.Office.Tools.Word.Controls.CheckBox(Globals.Factory, this.ItemProvider, this.HostContext, "5A60DFCA650141547CB5BE475E44E53E923655", "5A60DFCA650141547CB5BE475E44E53E923655", this, "checkBox58");
            this.checkBox59 = new Microsoft.Office.Tools.Word.Controls.CheckBox(Globals.Factory, this.ItemProvider, this.HostContext, "501D5B09453EA7542315B6F05CC7C4D64A6A15", "501D5B09453EA7542315B6F05CC7C4D64A6A15", this, "checkBox59");
            this.checkBox60 = new Microsoft.Office.Tools.Word.Controls.CheckBox(Globals.Factory, this.ItemProvider, this.HostContext, "587AA790E52B2754B05580ED5D1506F4F4DF35", "587AA790E52B2754B05580ED5D1506F4F4DF35", this, "checkBox60");
            this.checkBox61 = new Microsoft.Office.Tools.Word.Controls.CheckBox(Globals.Factory, this.ItemProvider, this.HostContext, "64E2BA49B69150645D06B783610DE45AC79A26", "64E2BA49B69150645D06B783610DE45AC79A26", this, "checkBox61");
            this.checkBox62 = new Microsoft.Office.Tools.Word.Controls.CheckBox(Globals.Factory, this.ItemProvider, this.HostContext, "67CA8707A6D6CF644E46AB0D6B9BCCE1F8C3F6", "67CA8707A6D6CF644E46AB0D6B9BCCE1F8C3F6", this, "checkBox62");
            this.checkBox63 = new Microsoft.Office.Tools.Word.Controls.CheckBox(Globals.Factory, this.ItemProvider, this.HostContext, "6E27E4B9F6513D64F906BAAF693CDC20684206", "6E27E4B9F6513D64F906BAAF693CDC20684206", this, "checkBox63");
            this.checkBox64 = new Microsoft.Office.Tools.Word.Controls.CheckBox(Globals.Factory, this.ItemProvider, this.HostContext, "630C66932608D664DBA69EE2690841AEFB92F6", "630C66932608D664DBA69EE2690841AEFB92F6", this, "checkBox64");
            this.checkBox65 = new Microsoft.Office.Tools.Word.Controls.CheckBox(Globals.Factory, this.ItemProvider, this.HostContext, "6AD65C7EF681806437068C2764B986A26603C6", "6AD65C7EF681806437068C2764B986A26603C6", this, "checkBox65");
            this.checkBox66 = new Microsoft.Office.Tools.Word.Controls.CheckBox(Globals.Factory, this.ItemProvider, this.HostContext, "65BDD79D1628E464BCB6B1946A9239BB303EE6", "65BDD79D1628E464BCB6B1946A9239BB303EE6", this, "checkBox66");
            this.checkBox67 = new Microsoft.Office.Tools.Word.Controls.CheckBox(Globals.Factory, this.ItemProvider, this.HostContext, "6DEB5D9F96C35B64FB8686F16407CF39E49D96", "6DEB5D9F96C35B64FB8686F16407CF39E49D96", this, "checkBox67");
            this.checkBox68 = new Microsoft.Office.Tools.Word.Controls.CheckBox(Globals.Factory, this.ItemProvider, this.HostContext, "6AEE74A976C49964BD7690886E497A3B59DBE6", "6AEE74A976C49964BD7690886E497A3B59DBE6", this, "checkBox68");
            this.checkBox69 = new Microsoft.Office.Tools.Word.Controls.CheckBox(Globals.Factory, this.ItemProvider, this.HostContext, "6121989F46E26E649746BACD6CBC145F2DEED6", "6121989F46E26E649746BACD6CBC145F2DEED6", this, "checkBox69");
            this.checkBox70 = new Microsoft.Office.Tools.Word.Controls.CheckBox(Globals.Factory, this.ItemProvider, this.HostContext, "6B4C931806D7D4649CD6A27F67474F77A132C6", "6B4C931806D7D4649CD6A27F67474F77A132C6", this, "checkBox70");
            this.checkBox71 = new Microsoft.Office.Tools.Word.Controls.CheckBox(Globals.Factory, this.ItemProvider, this.HostContext, "7AD03A2DD7A96F7416178F3A70C8C22E8A9297", "7AD03A2DD7A96F7416178F3A70C8C22E8A9297", this, "checkBox71");
            this.checkBox72 = new Microsoft.Office.Tools.Word.Controls.CheckBox(Globals.Factory, this.ItemProvider, this.HostContext, "7448C2F32772E674BC2795C878591CFEFFF197", "7448C2F32772E674BC2795C878591CFEFFF197", this, "checkBox72");
            this.checkBox73 = new Microsoft.Office.Tools.Word.Controls.CheckBox(Globals.Factory, this.ItemProvider, this.HostContext, "7774ADA42755D1748B179A4B798E2EFAA53C17", "7774ADA42755D1748B179A4B798E2EFAA53C17", this, "checkBox73");
            this.checkBox74 = new Microsoft.Office.Tools.Word.Controls.CheckBox(Globals.Factory, this.ItemProvider, this.HostContext, "70609F2927D5F9749987905A7243DDC7CD8817", "70609F2927D5F9749987905A7243DDC7CD8817", this, "checkBox74");
            this.checkBox75 = new Microsoft.Office.Tools.Word.Controls.CheckBox(Globals.Factory, this.ItemProvider, this.HostContext, "78BCC56BB75A9D74D187B47377A734ADF5BE87", "78BCC56BB75A9D74D187B47377A734ADF5BE87", this, "checkBox75");
            this.checkBox76 = new Microsoft.Office.Tools.Word.Controls.CheckBox(Globals.Factory, this.ItemProvider, this.HostContext, "7C6AD61547BF3C747387A1BA7DAB532AE2C447", "7C6AD61547BF3C747387A1BA7DAB532AE2C447", this, "checkBox76");
            this.checkBox77 = new Microsoft.Office.Tools.Word.Controls.CheckBox(Globals.Factory, this.ItemProvider, this.HostContext, "701075B2279E9A74E387814D749D9EAD730A87", "701075B2279E9A74E387814D749D9EAD730A87", this, "checkBox77");
            this.checkBox78 = new Microsoft.Office.Tools.Word.Controls.CheckBox(Globals.Factory, this.ItemProvider, this.HostContext, "7351D9882701FD74FCA783AF7D19751D904257", "7351D9882701FD74FCA783AF7D19751D904257", this, "checkBox78");
            this.checkBox79 = new Microsoft.Office.Tools.Word.Controls.CheckBox(Globals.Factory, this.ItemProvider, this.HostContext, "762010A607FC9D745577AEC87F4A4423A17D77", "762010A607FC9D745577AEC87F4A4423A17D77", this, "checkBox79");
            this.checkBox80 = new Microsoft.Office.Tools.Word.Controls.CheckBox(Globals.Factory, this.ItemProvider, this.HostContext, "876198DCA8DE1284F148A0E78525CA3AEF9458", "876198DCA8DE1284F148A0E78525CA3AEF9458", this, "checkBox80");
            this.checkBox81 = new Microsoft.Office.Tools.Word.Controls.CheckBox(Globals.Factory, this.ItemProvider, this.HostContext, "8C6EAE39788C9C848398BF248FAB8FCF2A3928", "8C6EAE39788C9C848398BF248FAB8FCF2A3928", this, "checkBox81");
            this.checkBox82 = new Microsoft.Office.Tools.Word.Controls.CheckBox(Globals.Factory, this.ItemProvider, this.HostContext, "81859976B8F01784D198936089846838780B08", "81859976B8F01784D198936089846838780B08", this, "checkBox82");
            this.checkBox86 = new Microsoft.Office.Tools.Word.Controls.CheckBox(Globals.Factory, this.ItemProvider, this.HostContext, "8CC31C11A8333584AC68A5D7834DFCAACFFB18", "8CC31C11A8333584AC68A5D7834DFCAACFFB18", this, "checkBox86");
            this.checkBox87 = new Microsoft.Office.Tools.Word.Controls.CheckBox(Globals.Factory, this.ItemProvider, this.HostContext, "85C89D0EE8F1B7843498BD7A865B97C4EA22E8", "85C89D0EE8F1B7843498BD7A865B97C4EA22E8", this, "checkBox87");
            this.checkBox88 = new Microsoft.Office.Tools.Word.Controls.CheckBox(Globals.Factory, this.ItemProvider, this.HostContext, "8E203167B8FDAA84B38895A1833C39AB0DFB68", "8E203167B8FDAA84B38895A1833C39AB0DFB68", this, "checkBox88");
            this.checkBox89 = new Microsoft.Office.Tools.Word.Controls.CheckBox(Globals.Factory, this.ItemProvider, this.HostContext, "849052CE98B85984C36888B58A67B83699F078", "849052CE98B85984C36888B58A67B83699F078", this, "checkBox89");
            this.checkBox90 = new Microsoft.Office.Tools.Word.Controls.CheckBox(Globals.Factory, this.ItemProvider, this.HostContext, "8ACEE6C698BC07842C38812D8C1DA6F3648698", "8ACEE6C698BC07842C38812D8C1DA6F3648698", this, "checkBox90");
            this.checkBox91 = new Microsoft.Office.Tools.Word.Controls.CheckBox(Globals.Factory, this.ItemProvider, this.HostContext, "8070056838444384F7D8B6C58335C33BDF6CB8", "8070056838444384F7D8B6C58335C33BDF6CB8", this, "checkBox91");
            this.checkBox92 = new Microsoft.Office.Tools.Word.Controls.CheckBox(Globals.Factory, this.ItemProvider, this.HostContext, "892F900688F2DC8453B8907A819FF1DC7707E8", "892F900688F2DC8453B8907A819FF1DC7707E8", this, "checkBox92");
            this.checkBox93 = new Microsoft.Office.Tools.Word.Controls.CheckBox(Globals.Factory, this.ItemProvider, this.HostContext, "92EAB2D1B93E1B948E59BBE49B8C3255D43B39", "92EAB2D1B93E1B948E59BBE49B8C3255D43B39", this, "checkBox93");
            this.checkBox94 = new Microsoft.Office.Tools.Word.Controls.CheckBox(Globals.Factory, this.ItemProvider, this.HostContext, "9E2BD12F19DBED94A689911B98786F6FF0B0D9", "9E2BD12F19DBED94A689911B98786F6FF0B0D9", this, "checkBox94");
            this.checkBox95 = new Microsoft.Office.Tools.Word.Controls.CheckBox(Globals.Factory, this.ItemProvider, this.HostContext, "9697CB247962FE948189877998FC4BEA624249", "9697CB247962FE948189877998FC4BEA624249", this, "checkBox95");
            this.checkBox96 = new Microsoft.Office.Tools.Word.Controls.CheckBox(Globals.Factory, this.ItemProvider, this.HostContext, "9B6A70AE999DFF94DFD9952F9937DD9980F729", "9B6A70AE999DFF94DFD9952F9937DD9980F729", this, "checkBox96");
            this.checkBox83 = new Microsoft.Office.Tools.Word.Controls.CheckBox(Globals.Factory, this.ItemProvider, this.HostContext, "907296DCA96B5E9498B9888B9EC740AB27BA49", "907296DCA96B5E9498B9888B9EC740AB27BA49", this, "checkBox83");
            this.checkBox84 = new Microsoft.Office.Tools.Word.Controls.CheckBox(Globals.Factory, this.ItemProvider, this.HostContext, "9C75D73CC9E1B4941F19B9419A4C8AD1B8F339", "9C75D73CC9E1B4941F19B9419A4C8AD1B8F339", this, "checkBox84");
            this.checkBox85 = new Microsoft.Office.Tools.Word.Controls.CheckBox(Globals.Factory, this.ItemProvider, this.HostContext, "911B013159042F9487B99D9794DE4B4B166A29", "911B013159042F9487B99D9794DE4B4B166A29", this, "checkBox85");
            this.checkBox99 = new Microsoft.Office.Tools.Word.Controls.CheckBox(Globals.Factory, this.ItemProvider, this.HostContext, "903F40ECD97915949089A3619979C74030AF79", "903F40ECD97915949089A3619979C74030AF79", this, "checkBox99");
            this.checkBox98 = new Microsoft.Office.Tools.Word.Controls.CheckBox(Globals.Factory, this.ItemProvider, this.HostContext, "92056EEC09495A940D498CBC97E5C38D9F1FF9", "92056EEC09495A940D498CBC97E5C38D9F1FF9", this, "checkBox98");
            this.checkBox97 = new Microsoft.Office.Tools.Word.Controls.CheckBox(Globals.Factory, this.ItemProvider, this.HostContext, "9101046389465D94C9C9B78091510A3FA4DF69", "9101046389465D94C9C9B78091510A3FA4DF69", this, "checkBox97");
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "15.0.0.0")]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void InitializeComponents() {
            // 
            // btnGerarXML
            // 
            this.btnGerarXML.BackColor = System.Drawing.SystemColors.Control;
            this.btnGerarXML.ForeColor = System.Drawing.SystemColors.ControlText;
            this.btnGerarXML.Name = "btnGerarXML";
            this.btnGerarXML.Text = "Gerar XML";
            this.btnGerarXML.UseVisualStyleBackColor = false;
            // 
            // checkBox01
            // 
            this.checkBox01.CheckAlign = System.Drawing.ContentAlignment.BottomCenter;
            this.checkBox01.Name = "checkBox01";
            // 
            // checkBox02
            // 
            this.checkBox02.CheckAlign = System.Drawing.ContentAlignment.BottomCenter;
            this.checkBox02.Name = "checkBox02";
            // 
            // checkBox03
            // 
            this.checkBox03.Name = "checkBox03";
            // 
            // checkBox04
            // 
            this.checkBox04.CheckAlign = System.Drawing.ContentAlignment.BottomCenter;
            this.checkBox04.ImageAlign = System.Drawing.ContentAlignment.TopLeft;
            this.checkBox04.Name = "checkBox04";
            // 
            // checkBox05
            // 
            this.checkBox05.Name = "checkBox05";
            // 
            // checkBox06
            // 
            this.checkBox06.Name = "checkBox06";
            // 
            // checkBox07
            // 
            this.checkBox07.Name = "checkBox07";
            // 
            // checkBox08
            // 
            this.checkBox08.Name = "checkBox08";
            // 
            // checkBox09
            // 
            this.checkBox09.Name = "checkBox09";
            // 
            // checkBox10
            // 
            this.checkBox10.Name = "checkBox10";
            // 
            // checkBox11
            // 
            this.checkBox11.Name = "checkBox11";
            // 
            // checkBox12
            // 
            this.checkBox12.Name = "checkBox12";
            // 
            // checkBox13
            // 
            this.checkBox13.Name = "checkBox13";
            // 
            // checkBox14
            // 
            this.checkBox14.Name = "checkBox14";
            // 
            // checkBox15
            // 
            this.checkBox15.Name = "checkBox15";
            // 
            // checkBox16
            // 
            this.checkBox16.Name = "checkBox16";
            // 
            // checkBox17
            // 
            this.checkBox17.Name = "checkBox17";
            // 
            // checkBox18
            // 
            this.checkBox18.Name = "checkBox18";
            // 
            // checkBox19
            // 
            this.checkBox19.Name = "checkBox19";
            // 
            // checkBox20
            // 
            this.checkBox20.Name = "checkBox20";
            // 
            // checkBox21
            // 
            this.checkBox21.Name = "checkBox21";
            // 
            // checkBox22
            // 
            this.checkBox22.Name = "checkBox22";
            // 
            // checkBox23
            // 
            this.checkBox23.Name = "checkBox23";
            // 
            // checkBox24
            // 
            this.checkBox24.Name = "checkBox24";
            // 
            // checkBox25
            // 
            this.checkBox25.Name = "checkBox25";
            // 
            // checkBox26
            // 
            this.checkBox26.Name = "checkBox26";
            // 
            // checkBox27
            // 
            this.checkBox27.Name = "checkBox27";
            // 
            // checkBox28
            // 
            this.checkBox28.Name = "checkBox28";
            // 
            // checkBox29
            // 
            this.checkBox29.Name = "checkBox29";
            // 
            // checkBox30
            // 
            this.checkBox30.Name = "checkBox30";
            // 
            // checkBox31
            // 
            this.checkBox31.Name = "checkBox31";
            // 
            // checkBox32
            // 
            this.checkBox32.Name = "checkBox32";
            // 
            // checkBox33
            // 
            this.checkBox33.Name = "checkBox33";
            // 
            // checkBox34
            // 
            this.checkBox34.Name = "checkBox34";
            // 
            // checkBox35
            // 
            this.checkBox35.Name = "checkBox35";
            // 
            // checkBox36
            // 
            this.checkBox36.Name = "checkBox36";
            // 
            // checkBox37
            // 
            this.checkBox37.Name = "checkBox37";
            // 
            // checkBox38
            // 
            this.checkBox38.Name = "checkBox38";
            // 
            // checkBox39
            // 
            this.checkBox39.Name = "checkBox39";
            // 
            // checkBox40
            // 
            this.checkBox40.Name = "checkBox40";
            // 
            // checkBox41
            // 
            this.checkBox41.Name = "checkBox41";
            // 
            // checkBox42
            // 
            this.checkBox42.Name = "checkBox42";
            // 
            // checkBox43
            // 
            this.checkBox43.Name = "checkBox43";
            // 
            // checkBox44
            // 
            this.checkBox44.Name = "checkBox44";
            // 
            // checkBox45
            // 
            this.checkBox45.Name = "checkBox45";
            // 
            // checkBox48
            // 
            this.checkBox48.Name = "checkBox48";
            // 
            // checkBox47
            // 
            this.checkBox47.Name = "checkBox47";
            // 
            // checkBox46
            // 
            this.checkBox46.Name = "checkBox46";
            // 
            // checkBox49
            // 
            this.checkBox49.Name = "checkBox49";
            // 
            // checkBox50
            // 
            this.checkBox50.Name = "checkBox50";
            // 
            // checkBox51
            // 
            this.checkBox51.Name = "checkBox51";
            // 
            // checkBox52
            // 
            this.checkBox52.Name = "checkBox52";
            // 
            // checkBox53
            // 
            this.checkBox53.Name = "checkBox53";
            // 
            // checkBox54
            // 
            this.checkBox54.Name = "checkBox54";
            // 
            // checkBox55
            // 
            this.checkBox55.Name = "checkBox55";
            // 
            // checkBox56
            // 
            this.checkBox56.Name = "checkBox56";
            // 
            // checkBox57
            // 
            this.checkBox57.Name = "checkBox57";
            // 
            // checkBox58
            // 
            this.checkBox58.Name = "checkBox58";
            // 
            // checkBox59
            // 
            this.checkBox59.Name = "checkBox59";
            // 
            // checkBox60
            // 
            this.checkBox60.Name = "checkBox60";
            // 
            // checkBox61
            // 
            this.checkBox61.Name = "checkBox61";
            // 
            // checkBox62
            // 
            this.checkBox62.Name = "checkBox62";
            // 
            // checkBox63
            // 
            this.checkBox63.Name = "checkBox63";
            // 
            // checkBox64
            // 
            this.checkBox64.Name = "checkBox64";
            // 
            // checkBox65
            // 
            this.checkBox65.Name = "checkBox65";
            // 
            // checkBox66
            // 
            this.checkBox66.Name = "checkBox66";
            // 
            // checkBox67
            // 
            this.checkBox67.Name = "checkBox67";
            // 
            // checkBox68
            // 
            this.checkBox68.Name = "checkBox68";
            // 
            // checkBox69
            // 
            this.checkBox69.Name = "checkBox69";
            // 
            // checkBox70
            // 
            this.checkBox70.Name = "checkBox70";
            // 
            // checkBox71
            // 
            this.checkBox71.Name = "checkBox71";
            // 
            // checkBox72
            // 
            this.checkBox72.Name = "checkBox72";
            // 
            // checkBox73
            // 
            this.checkBox73.Name = "checkBox73";
            // 
            // checkBox74
            // 
            this.checkBox74.Name = "checkBox74";
            // 
            // checkBox75
            // 
            this.checkBox75.Name = "checkBox75";
            // 
            // checkBox76
            // 
            this.checkBox76.BackgroundImageLayout = System.Windows.Forms.ImageLayout.None;
            this.checkBox76.Name = "checkBox76";
            // 
            // checkBox77
            // 
            this.checkBox77.Name = "checkBox77";
            // 
            // checkBox78
            // 
            this.checkBox78.Name = "checkBox78";
            // 
            // checkBox79
            // 
            this.checkBox79.Name = "checkBox79";
            // 
            // checkBox80
            // 
            this.checkBox80.Name = "checkBox80";
            // 
            // checkBox81
            // 
            this.checkBox81.Name = "checkBox81";
            // 
            // checkBox82
            // 
            this.checkBox82.Name = "checkBox82";
            // 
            // checkBox86
            // 
            this.checkBox86.Name = "checkBox86";
            // 
            // checkBox87
            // 
            this.checkBox87.Name = "checkBox87";
            // 
            // checkBox88
            // 
            this.checkBox88.Name = "checkBox88";
            // 
            // checkBox89
            // 
            this.checkBox89.Name = "checkBox89";
            // 
            // checkBox90
            // 
            this.checkBox90.Name = "checkBox90";
            // 
            // checkBox91
            // 
            this.checkBox91.Name = "checkBox91";
            // 
            // checkBox92
            // 
            this.checkBox92.Name = "checkBox92";
            // 
            // checkBox93
            // 
            this.checkBox93.Name = "checkBox93";
            // 
            // checkBox94
            // 
            this.checkBox94.Name = "checkBox94";
            // 
            // checkBox95
            // 
            this.checkBox95.Name = "checkBox95";
            // 
            // checkBox96
            // 
            this.checkBox96.Name = "checkBox96";
            // 
            // checkBox83
            // 
            this.checkBox83.Name = "checkBox83";
            // 
            // checkBox84
            // 
            this.checkBox84.Name = "checkBox84";
            // 
            // checkBox85
            // 
            this.checkBox85.Name = "checkBox85";
            // 
            // checkBox99
            // 
            this.checkBox99.Name = "checkBox99";
            // 
            // checkBox98
            // 
            this.checkBox98.Name = "checkBox98";
            // 
            // checkBox97
            // 
            this.checkBox97.Name = "checkBox97";
            // 
            // ActionsPane
            // 
            this.ActionsPane.AutoSize = false;
            this.ActionsPane.AutoValidate = System.Windows.Forms.AutoValidate.EnablePreventFocusChange;
            // 
            // comboBoxContentControl1
            // 
            this.comboBoxContentControl1.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // datePickerContentControl1
            // 
            this.datePickerContentControl1.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // ThisDocument
            // 
            this.btnGerarXML.BindingContext = this.BindingContext;
            this.checkBox01.BindingContext = this.BindingContext;
            this.checkBox02.BindingContext = this.BindingContext;
            this.checkBox03.BindingContext = this.BindingContext;
            this.checkBox04.BindingContext = this.BindingContext;
            this.checkBox05.BindingContext = this.BindingContext;
            this.checkBox06.BindingContext = this.BindingContext;
            this.checkBox07.BindingContext = this.BindingContext;
            this.checkBox08.BindingContext = this.BindingContext;
            this.checkBox09.BindingContext = this.BindingContext;
            this.checkBox10.BindingContext = this.BindingContext;
            this.checkBox11.BindingContext = this.BindingContext;
            this.checkBox12.BindingContext = this.BindingContext;
            this.checkBox13.BindingContext = this.BindingContext;
            this.checkBox14.BindingContext = this.BindingContext;
            this.checkBox15.BindingContext = this.BindingContext;
            this.checkBox16.BindingContext = this.BindingContext;
            this.checkBox17.BindingContext = this.BindingContext;
            this.checkBox18.BindingContext = this.BindingContext;
            this.checkBox19.BindingContext = this.BindingContext;
            this.checkBox20.BindingContext = this.BindingContext;
            this.checkBox21.BindingContext = this.BindingContext;
            this.checkBox22.BindingContext = this.BindingContext;
            this.checkBox23.BindingContext = this.BindingContext;
            this.checkBox24.BindingContext = this.BindingContext;
            this.checkBox25.BindingContext = this.BindingContext;
            this.checkBox26.BindingContext = this.BindingContext;
            this.checkBox27.BindingContext = this.BindingContext;
            this.checkBox28.BindingContext = this.BindingContext;
            this.checkBox29.BindingContext = this.BindingContext;
            this.checkBox30.BindingContext = this.BindingContext;
            this.checkBox31.BindingContext = this.BindingContext;
            this.checkBox32.BindingContext = this.BindingContext;
            this.checkBox33.BindingContext = this.BindingContext;
            this.checkBox34.BindingContext = this.BindingContext;
            this.checkBox35.BindingContext = this.BindingContext;
            this.checkBox36.BindingContext = this.BindingContext;
            this.checkBox37.BindingContext = this.BindingContext;
            this.checkBox38.BindingContext = this.BindingContext;
            this.checkBox39.BindingContext = this.BindingContext;
            this.checkBox40.BindingContext = this.BindingContext;
            this.checkBox41.BindingContext = this.BindingContext;
            this.checkBox42.BindingContext = this.BindingContext;
            this.checkBox43.BindingContext = this.BindingContext;
            this.checkBox44.BindingContext = this.BindingContext;
            this.checkBox45.BindingContext = this.BindingContext;
            this.checkBox48.BindingContext = this.BindingContext;
            this.checkBox47.BindingContext = this.BindingContext;
            this.checkBox46.BindingContext = this.BindingContext;
            this.checkBox49.BindingContext = this.BindingContext;
            this.checkBox50.BindingContext = this.BindingContext;
            this.checkBox51.BindingContext = this.BindingContext;
            this.checkBox52.BindingContext = this.BindingContext;
            this.checkBox53.BindingContext = this.BindingContext;
            this.checkBox54.BindingContext = this.BindingContext;
            this.checkBox55.BindingContext = this.BindingContext;
            this.checkBox56.BindingContext = this.BindingContext;
            this.checkBox57.BindingContext = this.BindingContext;
            this.checkBox58.BindingContext = this.BindingContext;
            this.checkBox59.BindingContext = this.BindingContext;
            this.checkBox60.BindingContext = this.BindingContext;
            this.checkBox61.BindingContext = this.BindingContext;
            this.checkBox62.BindingContext = this.BindingContext;
            this.checkBox63.BindingContext = this.BindingContext;
            this.checkBox64.BindingContext = this.BindingContext;
            this.checkBox65.BindingContext = this.BindingContext;
            this.checkBox66.BindingContext = this.BindingContext;
            this.checkBox67.BindingContext = this.BindingContext;
            this.checkBox68.BindingContext = this.BindingContext;
            this.checkBox69.BindingContext = this.BindingContext;
            this.checkBox70.BindingContext = this.BindingContext;
            this.checkBox71.BindingContext = this.BindingContext;
            this.checkBox72.BindingContext = this.BindingContext;
            this.checkBox73.BindingContext = this.BindingContext;
            this.checkBox74.BindingContext = this.BindingContext;
            this.checkBox75.BindingContext = this.BindingContext;
            this.checkBox76.BindingContext = this.BindingContext;
            this.checkBox77.BindingContext = this.BindingContext;
            this.checkBox78.BindingContext = this.BindingContext;
            this.checkBox79.BindingContext = this.BindingContext;
            this.checkBox80.BindingContext = this.BindingContext;
            this.checkBox81.BindingContext = this.BindingContext;
            this.checkBox82.BindingContext = this.BindingContext;
            this.checkBox86.BindingContext = this.BindingContext;
            this.checkBox87.BindingContext = this.BindingContext;
            this.checkBox88.BindingContext = this.BindingContext;
            this.checkBox89.BindingContext = this.BindingContext;
            this.checkBox90.BindingContext = this.BindingContext;
            this.checkBox91.BindingContext = this.BindingContext;
            this.checkBox92.BindingContext = this.BindingContext;
            this.checkBox93.BindingContext = this.BindingContext;
            this.checkBox94.BindingContext = this.BindingContext;
            this.checkBox95.BindingContext = this.BindingContext;
            this.checkBox96.BindingContext = this.BindingContext;
            this.checkBox83.BindingContext = this.BindingContext;
            this.checkBox84.BindingContext = this.BindingContext;
            this.checkBox85.BindingContext = this.BindingContext;
            this.checkBox99.BindingContext = this.BindingContext;
            this.checkBox98.BindingContext = this.BindingContext;
            this.checkBox97.BindingContext = this.BindingContext;
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        private bool NeedsFill(string MemberName) {
            return this.DataHost.NeedsFill(this, MemberName);
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "15.0.0.0")]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        protected override void OnShutdown() {
            this.datePickerContentControl1.Dispose();
            this.comboBoxContentControl1.Dispose();
            this.ActionsPane.Dispose();
            base.OnShutdown();
        }
    }
    
    /// 
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "15.0.0.0")]
    internal sealed partial class Globals {
        
        /// 
        private Globals() {
        }
        
        private static ThisDocument _ThisDocument;
        
        private static global::Microsoft.Office.Tools.Word.Factory _factory;
        
        private static ThisRibbonCollection _ThisRibbonCollection;
        
        internal static ThisDocument ThisDocument {
            get {
                return _ThisDocument;
            }
            set {
                if ((_ThisDocument == null)) {
                    _ThisDocument = value;
                }
                else {
                    throw new System.NotSupportedException();
                }
            }
        }
        
        internal static global::Microsoft.Office.Tools.Word.Factory Factory {
            get {
                return _factory;
            }
            set {
                if ((_factory == null)) {
                    _factory = value;
                }
                else {
                    throw new System.NotSupportedException();
                }
            }
        }
        
        internal static ThisRibbonCollection Ribbons {
            get {
                if ((_ThisRibbonCollection == null)) {
                    _ThisRibbonCollection = new ThisRibbonCollection(_factory.GetRibbonFactory());
                }
                return _ThisRibbonCollection;
            }
        }
    }
    
    /// 
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "15.0.0.0")]
    internal sealed partial class ThisRibbonCollection : Microsoft.Office.Tools.Ribbon.RibbonCollectionBase {
        
        /// 
        internal ThisRibbonCollection(global::Microsoft.Office.Tools.Ribbon.RibbonFactory factory) : 
                base(factory) {
        }
    }
}
